//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.31 at 09:45:21 AM CET 
//


package com.ups.xmlschema.ct.worldship.impexp.shipmentimport.v1_0_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GoodModel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GoodModel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="PrintOnSED" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PrintOnCO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PrintOnNAFTA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PrintOnSLI" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DescriptionOfGood" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PartNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TariffCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CountryOfOrigin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Units" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UnitOfMeasure" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UnitPrice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MarksAndNumbers" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NetWeight" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LicenseException" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LicenseNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LicenseExpirationDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ECCN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ScheduleBNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ScheduleBUnits1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UnitOfMeasure1" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GrossWeight" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LbsOrKgs" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ScheduleBUnits2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UnitOfMeasure2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DFM" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DDTCRegistrationNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DDTCSignificantMilitaryEquipmentIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DDTCEligiblePartyCertificationIndicator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DDTCUSMLCategoryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DDTCQuantity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DDTCUnitOfMeasure" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DDTCLicenseLineNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ExportCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NumberOfPackagesContainingGood" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PreferenceCriterion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Producer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MultipleCountriesTerritoriesOfOrigin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NetCostMethod" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NetCostPeriodStartDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NetCostPeriodEndDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="GoodID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GoodModel", propOrder = {

})
public class GoodModel {

    @XmlElement(name = "PrintOnSED")
    protected String printOnSED;
    @XmlElement(name = "PrintOnCO")
    protected String printOnCO;
    @XmlElement(name = "PrintOnNAFTA")
    protected String printOnNAFTA;
    @XmlElement(name = "PrintOnSLI")
    protected String printOnSLI;
    @XmlElement(name = "DescriptionOfGood")
    protected String descriptionOfGood;
    @XmlElement(name = "PartNumber")
    protected String partNumber;
    @XmlElement(name = "TariffCode")
    protected String tariffCode;
    @XmlElement(name = "CountryOfOrigin")
    protected String countryOfOrigin;
    @XmlElement(name = "Units")
    protected String units;
    @XmlElement(name = "UnitOfMeasure")
    protected String unitOfMeasure;
    @XmlElement(name = "UnitPrice")
    protected String unitPrice;
    @XmlElement(name = "Currency")
    protected String currency;
    @XmlElement(name = "MarksAndNumbers")
    protected String marksAndNumbers;
    @XmlElement(name = "NetWeight")
    protected String netWeight;
    @XmlElement(name = "LicenseException")
    protected String licenseException;
    @XmlElement(name = "LicenseNumber")
    protected String licenseNumber;
    @XmlElement(name = "LicenseExpirationDate")
    protected String licenseExpirationDate;
    @XmlElement(name = "ECCN")
    protected String eccn;
    @XmlElement(name = "ScheduleBNumber")
    protected String scheduleBNumber;
    @XmlElement(name = "ScheduleBUnits1")
    protected String scheduleBUnits1;
    @XmlElement(name = "UnitOfMeasure1")
    protected String unitOfMeasure1;
    @XmlElement(name = "GrossWeight")
    protected String grossWeight;
    @XmlElement(name = "LbsOrKgs")
    protected String lbsOrKgs;
    @XmlElement(name = "ScheduleBUnits2")
    protected String scheduleBUnits2;
    @XmlElement(name = "UnitOfMeasure2")
    protected String unitOfMeasure2;
    @XmlElement(name = "DFM")
    protected String dfm;
    @XmlElement(name = "DDTCRegistrationNumber")
    protected String ddtcRegistrationNumber;
    @XmlElement(name = "DDTCSignificantMilitaryEquipmentIndicator")
    protected String ddtcSignificantMilitaryEquipmentIndicator;
    @XmlElement(name = "DDTCEligiblePartyCertificationIndicator")
    protected String ddtcEligiblePartyCertificationIndicator;
    @XmlElement(name = "DDTCUSMLCategoryCode")
    protected String ddtcusmlCategoryCode;
    @XmlElement(name = "DDTCQuantity")
    protected String ddtcQuantity;
    @XmlElement(name = "DDTCUnitOfMeasure")
    protected String ddtcUnitOfMeasure;
    @XmlElement(name = "DDTCLicenseLineNumber")
    protected String ddtcLicenseLineNumber;
    @XmlElement(name = "ExportCode")
    protected String exportCode;
    @XmlElement(name = "NumberOfPackagesContainingGood")
    protected String numberOfPackagesContainingGood;
    @XmlElement(name = "PreferenceCriterion")
    protected String preferenceCriterion;
    @XmlElement(name = "Producer")
    protected String producer;
    @XmlElement(name = "MultipleCountriesTerritoriesOfOrigin")
    protected String multipleCountriesTerritoriesOfOrigin;
    @XmlElement(name = "NetCostMethod")
    protected String netCostMethod;
    @XmlElement(name = "NetCostPeriodStartDate")
    protected String netCostPeriodStartDate;
    @XmlElement(name = "NetCostPeriodEndDate")
    protected String netCostPeriodEndDate;
    @XmlElement(name = "GoodID")
    protected String goodID;

    /**
     * Gets the value of the printOnSED property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrintOnSED() {
        return printOnSED;
    }

    /**
     * Sets the value of the printOnSED property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrintOnSED(String value) {
        this.printOnSED = value;
    }

    /**
     * Gets the value of the printOnCO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrintOnCO() {
        return printOnCO;
    }

    /**
     * Sets the value of the printOnCO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrintOnCO(String value) {
        this.printOnCO = value;
    }

    /**
     * Gets the value of the printOnNAFTA property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrintOnNAFTA() {
        return printOnNAFTA;
    }

    /**
     * Sets the value of the printOnNAFTA property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrintOnNAFTA(String value) {
        this.printOnNAFTA = value;
    }

    /**
     * Gets the value of the printOnSLI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrintOnSLI() {
        return printOnSLI;
    }

    /**
     * Sets the value of the printOnSLI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrintOnSLI(String value) {
        this.printOnSLI = value;
    }

    /**
     * Gets the value of the descriptionOfGood property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescriptionOfGood() {
        return descriptionOfGood;
    }

    /**
     * Sets the value of the descriptionOfGood property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescriptionOfGood(String value) {
        this.descriptionOfGood = value;
    }

    /**
     * Gets the value of the partNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartNumber() {
        return partNumber;
    }

    /**
     * Sets the value of the partNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartNumber(String value) {
        this.partNumber = value;
    }

    /**
     * Gets the value of the tariffCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTariffCode() {
        return tariffCode;
    }

    /**
     * Sets the value of the tariffCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTariffCode(String value) {
        this.tariffCode = value;
    }

    /**
     * Gets the value of the countryOfOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryOfOrigin() {
        return countryOfOrigin;
    }

    /**
     * Sets the value of the countryOfOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryOfOrigin(String value) {
        this.countryOfOrigin = value;
    }

    /**
     * Gets the value of the units property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnits() {
        return units;
    }

    /**
     * Sets the value of the units property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnits(String value) {
        this.units = value;
    }

    /**
     * Gets the value of the unitOfMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitOfMeasure() {
        return unitOfMeasure;
    }

    /**
     * Sets the value of the unitOfMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitOfMeasure(String value) {
        this.unitOfMeasure = value;
    }

    /**
     * Gets the value of the unitPrice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitPrice() {
        return unitPrice;
    }

    /**
     * Sets the value of the unitPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitPrice(String value) {
        this.unitPrice = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the marksAndNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarksAndNumbers() {
        return marksAndNumbers;
    }

    /**
     * Sets the value of the marksAndNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarksAndNumbers(String value) {
        this.marksAndNumbers = value;
    }

    /**
     * Gets the value of the netWeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetWeight() {
        return netWeight;
    }

    /**
     * Sets the value of the netWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetWeight(String value) {
        this.netWeight = value;
    }

    /**
     * Gets the value of the licenseException property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicenseException() {
        return licenseException;
    }

    /**
     * Sets the value of the licenseException property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicenseException(String value) {
        this.licenseException = value;
    }

    /**
     * Gets the value of the licenseNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicenseNumber() {
        return licenseNumber;
    }

    /**
     * Sets the value of the licenseNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicenseNumber(String value) {
        this.licenseNumber = value;
    }

    /**
     * Gets the value of the licenseExpirationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLicenseExpirationDate() {
        return licenseExpirationDate;
    }

    /**
     * Sets the value of the licenseExpirationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLicenseExpirationDate(String value) {
        this.licenseExpirationDate = value;
    }

    /**
     * Gets the value of the eccn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getECCN() {
        return eccn;
    }

    /**
     * Sets the value of the eccn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setECCN(String value) {
        this.eccn = value;
    }

    /**
     * Gets the value of the scheduleBNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScheduleBNumber() {
        return scheduleBNumber;
    }

    /**
     * Sets the value of the scheduleBNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScheduleBNumber(String value) {
        this.scheduleBNumber = value;
    }

    /**
     * Gets the value of the scheduleBUnits1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScheduleBUnits1() {
        return scheduleBUnits1;
    }

    /**
     * Sets the value of the scheduleBUnits1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScheduleBUnits1(String value) {
        this.scheduleBUnits1 = value;
    }

    /**
     * Gets the value of the unitOfMeasure1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitOfMeasure1() {
        return unitOfMeasure1;
    }

    /**
     * Sets the value of the unitOfMeasure1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitOfMeasure1(String value) {
        this.unitOfMeasure1 = value;
    }

    /**
     * Gets the value of the grossWeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGrossWeight() {
        return grossWeight;
    }

    /**
     * Sets the value of the grossWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGrossWeight(String value) {
        this.grossWeight = value;
    }

    /**
     * Gets the value of the lbsOrKgs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLbsOrKgs() {
        return lbsOrKgs;
    }

    /**
     * Sets the value of the lbsOrKgs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLbsOrKgs(String value) {
        this.lbsOrKgs = value;
    }

    /**
     * Gets the value of the scheduleBUnits2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScheduleBUnits2() {
        return scheduleBUnits2;
    }

    /**
     * Sets the value of the scheduleBUnits2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScheduleBUnits2(String value) {
        this.scheduleBUnits2 = value;
    }

    /**
     * Gets the value of the unitOfMeasure2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitOfMeasure2() {
        return unitOfMeasure2;
    }

    /**
     * Sets the value of the unitOfMeasure2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitOfMeasure2(String value) {
        this.unitOfMeasure2 = value;
    }

    /**
     * Gets the value of the dfm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDFM() {
        return dfm;
    }

    /**
     * Sets the value of the dfm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDFM(String value) {
        this.dfm = value;
    }

    /**
     * Gets the value of the ddtcRegistrationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDDTCRegistrationNumber() {
        return ddtcRegistrationNumber;
    }

    /**
     * Sets the value of the ddtcRegistrationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDDTCRegistrationNumber(String value) {
        this.ddtcRegistrationNumber = value;
    }

    /**
     * Gets the value of the ddtcSignificantMilitaryEquipmentIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDDTCSignificantMilitaryEquipmentIndicator() {
        return ddtcSignificantMilitaryEquipmentIndicator;
    }

    /**
     * Sets the value of the ddtcSignificantMilitaryEquipmentIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDDTCSignificantMilitaryEquipmentIndicator(String value) {
        this.ddtcSignificantMilitaryEquipmentIndicator = value;
    }

    /**
     * Gets the value of the ddtcEligiblePartyCertificationIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDDTCEligiblePartyCertificationIndicator() {
        return ddtcEligiblePartyCertificationIndicator;
    }

    /**
     * Sets the value of the ddtcEligiblePartyCertificationIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDDTCEligiblePartyCertificationIndicator(String value) {
        this.ddtcEligiblePartyCertificationIndicator = value;
    }

    /**
     * Gets the value of the ddtcusmlCategoryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDDTCUSMLCategoryCode() {
        return ddtcusmlCategoryCode;
    }

    /**
     * Sets the value of the ddtcusmlCategoryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDDTCUSMLCategoryCode(String value) {
        this.ddtcusmlCategoryCode = value;
    }

    /**
     * Gets the value of the ddtcQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDDTCQuantity() {
        return ddtcQuantity;
    }

    /**
     * Sets the value of the ddtcQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDDTCQuantity(String value) {
        this.ddtcQuantity = value;
    }

    /**
     * Gets the value of the ddtcUnitOfMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDDTCUnitOfMeasure() {
        return ddtcUnitOfMeasure;
    }

    /**
     * Sets the value of the ddtcUnitOfMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDDTCUnitOfMeasure(String value) {
        this.ddtcUnitOfMeasure = value;
    }

    /**
     * Gets the value of the ddtcLicenseLineNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDDTCLicenseLineNumber() {
        return ddtcLicenseLineNumber;
    }

    /**
     * Sets the value of the ddtcLicenseLineNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDDTCLicenseLineNumber(String value) {
        this.ddtcLicenseLineNumber = value;
    }

    /**
     * Gets the value of the exportCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExportCode() {
        return exportCode;
    }

    /**
     * Sets the value of the exportCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExportCode(String value) {
        this.exportCode = value;
    }

    /**
     * Gets the value of the numberOfPackagesContainingGood property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumberOfPackagesContainingGood() {
        return numberOfPackagesContainingGood;
    }

    /**
     * Sets the value of the numberOfPackagesContainingGood property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumberOfPackagesContainingGood(String value) {
        this.numberOfPackagesContainingGood = value;
    }

    /**
     * Gets the value of the preferenceCriterion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPreferenceCriterion() {
        return preferenceCriterion;
    }

    /**
     * Sets the value of the preferenceCriterion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPreferenceCriterion(String value) {
        this.preferenceCriterion = value;
    }

    /**
     * Gets the value of the producer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProducer() {
        return producer;
    }

    /**
     * Sets the value of the producer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProducer(String value) {
        this.producer = value;
    }

    /**
     * Gets the value of the multipleCountriesTerritoriesOfOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMultipleCountriesTerritoriesOfOrigin() {
        return multipleCountriesTerritoriesOfOrigin;
    }

    /**
     * Sets the value of the multipleCountriesTerritoriesOfOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMultipleCountriesTerritoriesOfOrigin(String value) {
        this.multipleCountriesTerritoriesOfOrigin = value;
    }

    /**
     * Gets the value of the netCostMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetCostMethod() {
        return netCostMethod;
    }

    /**
     * Sets the value of the netCostMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetCostMethod(String value) {
        this.netCostMethod = value;
    }

    /**
     * Gets the value of the netCostPeriodStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetCostPeriodStartDate() {
        return netCostPeriodStartDate;
    }

    /**
     * Sets the value of the netCostPeriodStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetCostPeriodStartDate(String value) {
        this.netCostPeriodStartDate = value;
    }

    /**
     * Gets the value of the netCostPeriodEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNetCostPeriodEndDate() {
        return netCostPeriodEndDate;
    }

    /**
     * Sets the value of the netCostPeriodEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNetCostPeriodEndDate(String value) {
        this.netCostPeriodEndDate = value;
    }

    /**
     * Gets the value of the goodID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGoodID() {
        return goodID;
    }

    /**
     * Sets the value of the goodID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGoodID(String value) {
        this.goodID = value;
    }

}
