//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.31 at 09:45:21 AM CET 
//


package com.ups.xmlschema.ct.worldship.impexp.shipmentimport.v1_0_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HandlingUnitModel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HandlingUnitModel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="HUDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HUNumUnits" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HUType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HUHeight" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HUWidth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HULength" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HandlingUnitModel", propOrder = {

})
public class HandlingUnitModel {

    @XmlElement(name = "HUDescription")
    protected String huDescription;
    @XmlElement(name = "HUNumUnits")
    protected String huNumUnits;
    @XmlElement(name = "HUType")
    protected String huType;
    @XmlElement(name = "HUHeight")
    protected String huHeight;
    @XmlElement(name = "HUWidth")
    protected String huWidth;
    @XmlElement(name = "HULength")
    protected String huLength;

    /**
     * Gets the value of the huDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHUDescription() {
        return huDescription;
    }

    /**
     * Sets the value of the huDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHUDescription(String value) {
        this.huDescription = value;
    }

    /**
     * Gets the value of the huNumUnits property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHUNumUnits() {
        return huNumUnits;
    }

    /**
     * Sets the value of the huNumUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHUNumUnits(String value) {
        this.huNumUnits = value;
    }

    /**
     * Gets the value of the huType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHUType() {
        return huType;
    }

    /**
     * Sets the value of the huType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHUType(String value) {
        this.huType = value;
    }

    /**
     * Gets the value of the huHeight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHUHeight() {
        return huHeight;
    }

    /**
     * Sets the value of the huHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHUHeight(String value) {
        this.huHeight = value;
    }

    /**
     * Gets the value of the huWidth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHUWidth() {
        return huWidth;
    }

    /**
     * Sets the value of the huWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHUWidth(String value) {
        this.huWidth = value;
    }

    /**
     * Gets the value of the huLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHULength() {
        return huLength;
    }

    /**
     * Sets the value of the huLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHULength(String value) {
        this.huLength = value;
    }

}
