//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.31 at 09:45:21 AM CET 
//


package com.ups.xmlschema.ct.worldship.impexp.shipmentimport.v1_0_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InternationalDocumentationModel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InternationalDocumentationModel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="CreateAnInvoice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ImporterSameAsShipTo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Invoice" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="TermsOfSale" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="ReasonForExport" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="DeclarationStatement" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="AdditionalComments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="LineTotal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Charges" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;all>
 *                             &lt;element name="Discount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Freight" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Insurance" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="Other" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                           &lt;/all>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CustomsValue" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="Total" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Origin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="SED" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="PartiesToTransaction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="UltimateConsigneeSameAsShipTo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="CountryTerritoryOfUltimateDestination" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="AESTransactionNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="AESTransactionNumberType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="RoutedTransaction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="CurrencyConversion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="CO" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="UPSPrepareCO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="OwnerOrAgent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="NAFTACO" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="Producer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="BlanketPeriodStart" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="BlanketPeriodEnd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="MovementReferenceNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CN22" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="GoodsType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="GoodsTypeOtherDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="RequestDutiesAndTaxes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="Option" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InternationalDocumentationModel", propOrder = {

})
public class InternationalDocumentationModel {

    @XmlElement(name = "CreateAnInvoice")
    protected String createAnInvoice;
    @XmlElement(name = "Currency")
    protected String currency;
    @XmlElement(name = "ImporterSameAsShipTo")
    protected String importerSameAsShipTo;
    @XmlElement(name = "Invoice")
    protected InternationalDocumentationModel.Invoice invoice;
    @XmlElement(name = "CustomsValue")
    protected InternationalDocumentationModel.CustomsValue customsValue;
    @XmlElement(name = "SED")
    protected InternationalDocumentationModel.SED sed;
    @XmlElement(name = "CO")
    protected InternationalDocumentationModel.CO co;
    @XmlElement(name = "NAFTACO")
    protected InternationalDocumentationModel.NAFTACO naftaco;
    @XmlElement(name = "MovementReferenceNumber")
    protected String movementReferenceNumber;
    @XmlElement(name = "CN22")
    protected InternationalDocumentationModel.CN22 cn22;
    @XmlElement(name = "RequestDutiesAndTaxes")
    protected InternationalDocumentationModel.RequestDutiesAndTaxes requestDutiesAndTaxes;

    /**
     * Gets the value of the createAnInvoice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreateAnInvoice() {
        return createAnInvoice;
    }

    /**
     * Sets the value of the createAnInvoice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreateAnInvoice(String value) {
        this.createAnInvoice = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the importerSameAsShipTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImporterSameAsShipTo() {
        return importerSameAsShipTo;
    }

    /**
     * Sets the value of the importerSameAsShipTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImporterSameAsShipTo(String value) {
        this.importerSameAsShipTo = value;
    }

    /**
     * Gets the value of the invoice property.
     * 
     * @return
     *     possible object is
     *     {@link InternationalDocumentationModel.Invoice }
     *     
     */
    public InternationalDocumentationModel.Invoice getInvoice() {
        return invoice;
    }

    /**
     * Sets the value of the invoice property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternationalDocumentationModel.Invoice }
     *     
     */
    public void setInvoice(InternationalDocumentationModel.Invoice value) {
        this.invoice = value;
    }

    /**
     * Gets the value of the customsValue property.
     * 
     * @return
     *     possible object is
     *     {@link InternationalDocumentationModel.CustomsValue }
     *     
     */
    public InternationalDocumentationModel.CustomsValue getCustomsValue() {
        return customsValue;
    }

    /**
     * Sets the value of the customsValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternationalDocumentationModel.CustomsValue }
     *     
     */
    public void setCustomsValue(InternationalDocumentationModel.CustomsValue value) {
        this.customsValue = value;
    }

    /**
     * Gets the value of the sed property.
     * 
     * @return
     *     possible object is
     *     {@link InternationalDocumentationModel.SED }
     *     
     */
    public InternationalDocumentationModel.SED getSED() {
        return sed;
    }

    /**
     * Sets the value of the sed property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternationalDocumentationModel.SED }
     *     
     */
    public void setSED(InternationalDocumentationModel.SED value) {
        this.sed = value;
    }

    /**
     * Gets the value of the co property.
     * 
     * @return
     *     possible object is
     *     {@link InternationalDocumentationModel.CO }
     *     
     */
    public InternationalDocumentationModel.CO getCO() {
        return co;
    }

    /**
     * Sets the value of the co property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternationalDocumentationModel.CO }
     *     
     */
    public void setCO(InternationalDocumentationModel.CO value) {
        this.co = value;
    }

    /**
     * Gets the value of the naftaco property.
     * 
     * @return
     *     possible object is
     *     {@link InternationalDocumentationModel.NAFTACO }
     *     
     */
    public InternationalDocumentationModel.NAFTACO getNAFTACO() {
        return naftaco;
    }

    /**
     * Sets the value of the naftaco property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternationalDocumentationModel.NAFTACO }
     *     
     */
    public void setNAFTACO(InternationalDocumentationModel.NAFTACO value) {
        this.naftaco = value;
    }

    /**
     * Gets the value of the movementReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMovementReferenceNumber() {
        return movementReferenceNumber;
    }

    /**
     * Sets the value of the movementReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMovementReferenceNumber(String value) {
        this.movementReferenceNumber = value;
    }

    /**
     * Gets the value of the cn22 property.
     * 
     * @return
     *     possible object is
     *     {@link InternationalDocumentationModel.CN22 }
     *     
     */
    public InternationalDocumentationModel.CN22 getCN22() {
        return cn22;
    }

    /**
     * Sets the value of the cn22 property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternationalDocumentationModel.CN22 }
     *     
     */
    public void setCN22(InternationalDocumentationModel.CN22 value) {
        this.cn22 = value;
    }

    /**
     * Gets the value of the requestDutiesAndTaxes property.
     * 
     * @return
     *     possible object is
     *     {@link InternationalDocumentationModel.RequestDutiesAndTaxes }
     *     
     */
    public InternationalDocumentationModel.RequestDutiesAndTaxes getRequestDutiesAndTaxes() {
        return requestDutiesAndTaxes;
    }

    /**
     * Sets the value of the requestDutiesAndTaxes property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternationalDocumentationModel.RequestDutiesAndTaxes }
     *     
     */
    public void setRequestDutiesAndTaxes(InternationalDocumentationModel.RequestDutiesAndTaxes value) {
        this.requestDutiesAndTaxes = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="GoodsType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="GoodsTypeOtherDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class CN22 {

        @XmlElement(name = "GoodsType")
        protected String goodsType;
        @XmlElement(name = "GoodsTypeOtherDescription")
        protected String goodsTypeOtherDescription;

        /**
         * Gets the value of the goodsType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGoodsType() {
            return goodsType;
        }

        /**
         * Sets the value of the goodsType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGoodsType(String value) {
            this.goodsType = value;
        }

        /**
         * Gets the value of the goodsTypeOtherDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGoodsTypeOtherDescription() {
            return goodsTypeOtherDescription;
        }

        /**
         * Sets the value of the goodsTypeOtherDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGoodsTypeOtherDescription(String value) {
            this.goodsTypeOtherDescription = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="UPSPrepareCO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="OwnerOrAgent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class CO {

        @XmlElement(name = "UPSPrepareCO")
        protected String upsPrepareCO;
        @XmlElement(name = "OwnerOrAgent")
        protected String ownerOrAgent;

        /**
         * Gets the value of the upsPrepareCO property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUPSPrepareCO() {
            return upsPrepareCO;
        }

        /**
         * Sets the value of the upsPrepareCO property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUPSPrepareCO(String value) {
            this.upsPrepareCO = value;
        }

        /**
         * Gets the value of the ownerOrAgent property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOwnerOrAgent() {
            return ownerOrAgent;
        }

        /**
         * Sets the value of the ownerOrAgent property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOwnerOrAgent(String value) {
            this.ownerOrAgent = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="Total" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Currency" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Origin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class CustomsValue {

        @XmlElement(name = "Total")
        protected String total;
        @XmlElement(name = "Currency")
        protected String currency;
        @XmlElement(name = "Origin")
        protected String origin;

        /**
         * Gets the value of the total property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTotal() {
            return total;
        }

        /**
         * Sets the value of the total property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTotal(String value) {
            this.total = value;
        }

        /**
         * Gets the value of the currency property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCurrency() {
            return currency;
        }

        /**
         * Sets the value of the currency property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCurrency(String value) {
            this.currency = value;
        }

        /**
         * Gets the value of the origin property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrigin() {
            return origin;
        }

        /**
         * Sets the value of the origin property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrigin(String value) {
            this.origin = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="TermsOfSale" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="ReasonForExport" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="DeclarationStatement" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="AdditionalComments" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="LineTotal" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Charges" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;all>
     *                   &lt;element name="Discount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Freight" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Insurance" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="Other" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                 &lt;/all>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class Invoice {

        @XmlElement(name = "TermsOfSale")
        protected String termsOfSale;
        @XmlElement(name = "ReasonForExport")
        protected String reasonForExport;
        @XmlElement(name = "DeclarationStatement")
        protected String declarationStatement;
        @XmlElement(name = "AdditionalComments")
        protected String additionalComments;
        @XmlElement(name = "LineTotal")
        protected String lineTotal;
        @XmlElement(name = "Charges")
        protected InternationalDocumentationModel.Invoice.Charges charges;

        /**
         * Gets the value of the termsOfSale property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTermsOfSale() {
            return termsOfSale;
        }

        /**
         * Sets the value of the termsOfSale property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTermsOfSale(String value) {
            this.termsOfSale = value;
        }

        /**
         * Gets the value of the reasonForExport property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReasonForExport() {
            return reasonForExport;
        }

        /**
         * Sets the value of the reasonForExport property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReasonForExport(String value) {
            this.reasonForExport = value;
        }

        /**
         * Gets the value of the declarationStatement property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDeclarationStatement() {
            return declarationStatement;
        }

        /**
         * Sets the value of the declarationStatement property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDeclarationStatement(String value) {
            this.declarationStatement = value;
        }

        /**
         * Gets the value of the additionalComments property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAdditionalComments() {
            return additionalComments;
        }

        /**
         * Sets the value of the additionalComments property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAdditionalComments(String value) {
            this.additionalComments = value;
        }

        /**
         * Gets the value of the lineTotal property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLineTotal() {
            return lineTotal;
        }

        /**
         * Sets the value of the lineTotal property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLineTotal(String value) {
            this.lineTotal = value;
        }

        /**
         * Gets the value of the charges property.
         * 
         * @return
         *     possible object is
         *     {@link InternationalDocumentationModel.Invoice.Charges }
         *     
         */
        public InternationalDocumentationModel.Invoice.Charges getCharges() {
            return charges;
        }

        /**
         * Sets the value of the charges property.
         * 
         * @param value
         *     allowed object is
         *     {@link InternationalDocumentationModel.Invoice.Charges }
         *     
         */
        public void setCharges(InternationalDocumentationModel.Invoice.Charges value) {
            this.charges = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;all>
         *         &lt;element name="Discount" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Freight" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Insurance" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="Other" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *       &lt;/all>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {

        })
        public static class Charges {

            @XmlElement(name = "Discount")
            protected String discount;
            @XmlElement(name = "Freight")
            protected String freight;
            @XmlElement(name = "Insurance")
            protected String insurance;
            @XmlElement(name = "Other")
            protected String other;

            /**
             * Gets the value of the discount property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDiscount() {
                return discount;
            }

            /**
             * Sets the value of the discount property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDiscount(String value) {
                this.discount = value;
            }

            /**
             * Gets the value of the freight property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFreight() {
                return freight;
            }

            /**
             * Sets the value of the freight property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFreight(String value) {
                this.freight = value;
            }

            /**
             * Gets the value of the insurance property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInsurance() {
                return insurance;
            }

            /**
             * Sets the value of the insurance property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInsurance(String value) {
                this.insurance = value;
            }

            /**
             * Gets the value of the other property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOther() {
                return other;
            }

            /**
             * Sets the value of the other property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOther(String value) {
                this.other = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="Producer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="BlanketPeriodStart" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="BlanketPeriodEnd" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class NAFTACO {

        @XmlElement(name = "Producer")
        protected String producer;
        @XmlElement(name = "BlanketPeriodStart")
        protected String blanketPeriodStart;
        @XmlElement(name = "BlanketPeriodEnd")
        protected String blanketPeriodEnd;

        /**
         * Gets the value of the producer property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProducer() {
            return producer;
        }

        /**
         * Sets the value of the producer property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProducer(String value) {
            this.producer = value;
        }

        /**
         * Gets the value of the blanketPeriodStart property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBlanketPeriodStart() {
            return blanketPeriodStart;
        }

        /**
         * Sets the value of the blanketPeriodStart property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBlanketPeriodStart(String value) {
            this.blanketPeriodStart = value;
        }

        /**
         * Gets the value of the blanketPeriodEnd property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBlanketPeriodEnd() {
            return blanketPeriodEnd;
        }

        /**
         * Sets the value of the blanketPeriodEnd property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBlanketPeriodEnd(String value) {
            this.blanketPeriodEnd = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="Option" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class RequestDutiesAndTaxes {

        @XmlElement(name = "Option")
        protected String option;

        /**
         * Gets the value of the option property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOption() {
            return option;
        }

        /**
         * Sets the value of the option property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOption(String value) {
            this.option = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="Code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="PartiesToTransaction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="UltimateConsigneeSameAsShipTo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="CountryTerritoryOfUltimateDestination" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="AESTransactionNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="AESTransactionNumberType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="RoutedTransaction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="CurrencyConversion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class SED {

        @XmlElement(name = "Code")
        protected String code;
        @XmlElement(name = "PartiesToTransaction")
        protected String partiesToTransaction;
        @XmlElement(name = "UltimateConsigneeSameAsShipTo")
        protected String ultimateConsigneeSameAsShipTo;
        @XmlElement(name = "CountryTerritoryOfUltimateDestination")
        protected String countryTerritoryOfUltimateDestination;
        @XmlElement(name = "AESTransactionNumber")
        protected String aesTransactionNumber;
        @XmlElement(name = "AESTransactionNumberType")
        protected String aesTransactionNumberType;
        @XmlElement(name = "RoutedTransaction")
        protected String routedTransaction;
        @XmlElement(name = "CurrencyConversion")
        protected String currencyConversion;

        /**
         * Gets the value of the code property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCode(String value) {
            this.code = value;
        }

        /**
         * Gets the value of the partiesToTransaction property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPartiesToTransaction() {
            return partiesToTransaction;
        }

        /**
         * Sets the value of the partiesToTransaction property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPartiesToTransaction(String value) {
            this.partiesToTransaction = value;
        }

        /**
         * Gets the value of the ultimateConsigneeSameAsShipTo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUltimateConsigneeSameAsShipTo() {
            return ultimateConsigneeSameAsShipTo;
        }

        /**
         * Sets the value of the ultimateConsigneeSameAsShipTo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUltimateConsigneeSameAsShipTo(String value) {
            this.ultimateConsigneeSameAsShipTo = value;
        }

        /**
         * Gets the value of the countryTerritoryOfUltimateDestination property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountryTerritoryOfUltimateDestination() {
            return countryTerritoryOfUltimateDestination;
        }

        /**
         * Sets the value of the countryTerritoryOfUltimateDestination property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountryTerritoryOfUltimateDestination(String value) {
            this.countryTerritoryOfUltimateDestination = value;
        }

        /**
         * Gets the value of the aesTransactionNumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAESTransactionNumber() {
            return aesTransactionNumber;
        }

        /**
         * Sets the value of the aesTransactionNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAESTransactionNumber(String value) {
            this.aesTransactionNumber = value;
        }

        /**
         * Gets the value of the aesTransactionNumberType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAESTransactionNumberType() {
            return aesTransactionNumberType;
        }

        /**
         * Sets the value of the aesTransactionNumberType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAESTransactionNumberType(String value) {
            this.aesTransactionNumberType = value;
        }

        /**
         * Gets the value of the routedTransaction property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRoutedTransaction() {
            return routedTransaction;
        }

        /**
         * Sets the value of the routedTransaction property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRoutedTransaction(String value) {
            this.routedTransaction = value;
        }

        /**
         * Gets the value of the currencyConversion property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCurrencyConversion() {
            return currencyConversion;
        }

        /**
         * Sets the value of the currencyConversion property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCurrencyConversion(String value) {
            this.currencyConversion = value;
        }

    }

}
