//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.31 at 09:45:21 AM CET 
//


package com.ups.xmlschema.ct.worldship.impexp.shipmentimport.v1_0_0;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ups.xmlschema.ct.worldship.impexp.shipmentimport.v1_0_0 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ups.xmlschema.ct.worldship.impexp.shipmentimport.v1_0_0
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ShipmentInformationModel.ShipmentOptions.ReturnsFlexibleAccess }
     * 
     */
    public ShipmentInformationModel.ShipmentOptions.ReturnsFlexibleAccess createShipmentInformationModelShipmentOptionsReturnsFlexibleAccess() {
        return new ShipmentInformationModel.ShipmentOptions.ReturnsFlexibleAccess();
    }

    /**
     * Create an instance of {@link LTLTLineItemModel }
     * 
     */
    public LTLTLineItemModel createLTLTLineItemModel() {
        return new LTLTLineItemModel();
    }

    /**
     * Create an instance of {@link ShipmentModel.PrinterID }
     * 
     */
    public ShipmentModel.PrinterID createShipmentModelPrinterID() {
        return new ShipmentModel.PrinterID();
    }

    /**
     * Create an instance of {@link ShipmentInformationModel.ShipmentOptions.ReturnOfDocument }
     * 
     */
    public ShipmentInformationModel.ShipmentOptions.ReturnOfDocument createShipmentInformationModelShipmentOptionsReturnOfDocument() {
        return new ShipmentInformationModel.ShipmentOptions.ReturnOfDocument();
    }

    /**
     * Create an instance of {@link ImporterModel }
     * 
     */
    public ImporterModel createImporterModel() {
        return new ImporterModel();
    }

    /**
     * Create an instance of {@link ShipmentInformationModel.ShipmentOptions.InternationalSpecialCommodities }
     * 
     */
    public ShipmentInformationModel.ShipmentOptions.InternationalSpecialCommodities createShipmentInformationModelShipmentOptionsInternationalSpecialCommodities() {
        return new ShipmentInformationModel.ShipmentOptions.InternationalSpecialCommodities();
    }

    /**
     * Create an instance of {@link ThirdPartyModel }
     * 
     */
    public ThirdPartyModel createThirdPartyModel() {
        return new ThirdPartyModel();
    }

    /**
     * Create an instance of {@link ShipmentInformationModel.ShipmentOptions.PreAlertNotification }
     * 
     */
    public ShipmentInformationModel.ShipmentOptions.PreAlertNotification createShipmentInformationModelShipmentOptionsPreAlertNotification() {
        return new ShipmentInformationModel.ShipmentOptions.PreAlertNotification();
    }

    /**
     * Create an instance of {@link UserFormsModel }
     * 
     */
    public UserFormsModel createUserFormsModel() {
        return new UserFormsModel();
    }

    /**
     * Create an instance of {@link ShipFromModel }
     * 
     */
    public ShipFromModel createShipFromModel() {
        return new ShipFromModel();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.FreightOptions.EmailNotification }
     * 
     */
    public FreightShipmentInformationModel.FreightOptions.EmailNotification createFreightShipmentInformationModelFreightOptionsEmailNotification() {
        return new FreightShipmentInformationModel.FreightOptions.EmailNotification();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel }
     * 
     */
    public FreightShipmentInformationModel createFreightShipmentInformationModel() {
        return new FreightShipmentInformationModel();
    }

    /**
     * Create an instance of {@link ShipmentInformationModel.ShipmentOptions.DeliveryConfirmation }
     * 
     */
    public ShipmentInformationModel.ShipmentOptions.DeliveryConfirmation createShipmentInformationModelShipmentOptionsDeliveryConfirmation() {
        return new ShipmentInformationModel.ShipmentOptions.DeliveryConfirmation();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.PickupNotificationsForLTL }
     * 
     */
    public FreightShipmentInformationModel.PickupNotificationsForLTL createFreightShipmentInformationModelPickupNotificationsForLTL() {
        return new FreightShipmentInformationModel.PickupNotificationsForLTL();
    }

    /**
     * Create an instance of {@link InternationalDocumentationModel.SED }
     * 
     */
    public InternationalDocumentationModel.SED createInternationalDocumentationModelSED() {
        return new InternationalDocumentationModel.SED();
    }

    /**
     * Create an instance of {@link ShipperLetterOfInstructionModel }
     * 
     */
    public ShipperLetterOfInstructionModel createShipperLetterOfInstructionModel() {
        return new ShipperLetterOfInstructionModel();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.FreightOptions.InsideDelivery }
     * 
     */
    public FreightShipmentInformationModel.FreightOptions.InsideDelivery createFreightShipmentInformationModelFreightOptionsInsideDelivery() {
        return new FreightShipmentInformationModel.FreightOptions.InsideDelivery();
    }

    /**
     * Create an instance of {@link ProducerModel }
     * 
     */
    public ProducerModel createProducerModel() {
        return new ProducerModel();
    }

    /**
     * Create an instance of {@link PackageModel.PackageOptions.DryIce }
     * 
     */
    public PackageModel.PackageOptions.DryIce createPackageModelPackageOptionsDryIce() {
        return new PackageModel.PackageOptions.DryIce();
    }

    /**
     * Create an instance of {@link PackageModel }
     * 
     */
    public PackageModel createPackageModel() {
        return new PackageModel();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.FreightOptions.HolidayDelivery }
     * 
     */
    public FreightShipmentInformationModel.FreightOptions.HolidayDelivery createFreightShipmentInformationModelFreightOptionsHolidayDelivery() {
        return new FreightShipmentInformationModel.FreightOptions.HolidayDelivery();
    }

    /**
     * Create an instance of {@link PackageModel.PackageOptions.QVN.Recipients }
     * 
     */
    public PackageModel.PackageOptions.QVN.Recipients createPackageModelPackageOptionsQVNRecipients() {
        return new PackageModel.PackageOptions.QVN.Recipients();
    }

    /**
     * Create an instance of {@link PackageModel.PackageOptions.VerbalConfirmation }
     * 
     */
    public PackageModel.PackageOptions.VerbalConfirmation createPackageModelPackageOptionsVerbalConfirmation() {
        return new PackageModel.PackageOptions.VerbalConfirmation();
    }

    /**
     * Create an instance of {@link UltimateConsigneeModel }
     * 
     */
    public UltimateConsigneeModel createUltimateConsigneeModel() {
        return new UltimateConsigneeModel();
    }

    /**
     * Create an instance of {@link ShipmentInformationModel.ShipmentOptions.UPSCarbonNeutral }
     * 
     */
    public ShipmentInformationModel.ShipmentOptions.UPSCarbonNeutral createShipmentInformationModelShipmentOptionsUPSCarbonNeutral() {
        return new ShipmentInformationModel.ShipmentOptions.UPSCarbonNeutral();
    }

    /**
     * Create an instance of {@link ShipmentInformationModel.ShipmentOptions.PreAlertNotification.SMSText }
     * 
     */
    public ShipmentInformationModel.ShipmentOptions.PreAlertNotification.SMSText createShipmentInformationModelShipmentOptionsPreAlertNotificationSMSText() {
        return new ShipmentInformationModel.ShipmentOptions.PreAlertNotification.SMSText();
    }

    /**
     * Create an instance of {@link ShipmentInformationModel.ShipmentOptions.QVN }
     * 
     */
    public ShipmentInformationModel.ShipmentOptions.QVN createShipmentInformationModelShipmentOptionsQVN() {
        return new ShipmentInformationModel.ShipmentOptions.QVN();
    }

    /**
     * Create an instance of {@link LTLTLLineItemsModel }
     * 
     */
    public LTLTLLineItemsModel createLTLTLLineItemsModel() {
        return new LTLTLLineItemsModel();
    }

    /**
     * Create an instance of {@link InternationalDocumentationModel.CustomsValue }
     * 
     */
    public InternationalDocumentationModel.CustomsValue createInternationalDocumentationModelCustomsValue() {
        return new InternationalDocumentationModel.CustomsValue();
    }

    /**
     * Create an instance of {@link FreightCommoditiesModel }
     * 
     */
    public FreightCommoditiesModel createFreightCommoditiesModel() {
        return new FreightCommoditiesModel();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.FreightOptions.LimitedAccessDelivery }
     * 
     */
    public FreightShipmentInformationModel.FreightOptions.LimitedAccessDelivery createFreightShipmentInformationModelFreightOptionsLimitedAccessDelivery() {
        return new FreightShipmentInformationModel.FreightOptions.LimitedAccessDelivery();
    }

    /**
     * Create an instance of {@link IntermediateConsigneeModel }
     * 
     */
    public IntermediateConsigneeModel createIntermediateConsigneeModel() {
        return new IntermediateConsigneeModel();
    }

    /**
     * Create an instance of {@link PackageModel.PackageOptions.AdditionalHandling }
     * 
     */
    public PackageModel.PackageOptions.AdditionalHandling createPackageModelPackageOptionsAdditionalHandling() {
        return new PackageModel.PackageOptions.AdditionalHandling();
    }

    /**
     * Create an instance of {@link ThirdPartyReceiverModel }
     * 
     */
    public ThirdPartyReceiverModel createThirdPartyReceiverModel() {
        return new ThirdPartyReceiverModel();
    }

    /**
     * Create an instance of {@link ShipmentInformationModel.ShipmentOptions.UPSReturnsPackAndCollect }
     * 
     */
    public ShipmentInformationModel.ShipmentOptions.UPSReturnsPackAndCollect createShipmentInformationModelShipmentOptionsUPSReturnsPackAndCollect() {
        return new ShipmentInformationModel.ShipmentOptions.UPSReturnsPackAndCollect();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.FreightOptions.LiftGateServiceForPickup }
     * 
     */
    public FreightShipmentInformationModel.FreightOptions.LiftGateServiceForPickup createFreightShipmentInformationModelFreightOptionsLiftGateServiceForPickup() {
        return new FreightShipmentInformationModel.FreightOptions.LiftGateServiceForPickup();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.FreightOptions.PickupAtUPSLocation }
     * 
     */
    public FreightShipmentInformationModel.FreightOptions.PickupAtUPSLocation createFreightShipmentInformationModelFreightOptionsPickupAtUPSLocation() {
        return new FreightShipmentInformationModel.FreightOptions.PickupAtUPSLocation();
    }

    /**
     * Create an instance of {@link InternationalDocumentationModel.NAFTACO }
     * 
     */
    public InternationalDocumentationModel.NAFTACO createInternationalDocumentationModelNAFTACO() {
        return new InternationalDocumentationModel.NAFTACO();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.PickupNotificationsForLTL.Recipients }
     * 
     */
    public FreightShipmentInformationModel.PickupNotificationsForLTL.Recipients createFreightShipmentInformationModelPickupNotificationsForLTLRecipients() {
        return new FreightShipmentInformationModel.PickupNotificationsForLTL.Recipients();
    }

    /**
     * Create an instance of {@link GoodsModel }
     * 
     */
    public GoodsModel createGoodsModel() {
        return new GoodsModel();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.FreightOptions.WeekendPickup }
     * 
     */
    public FreightShipmentInformationModel.FreightOptions.WeekendPickup createFreightShipmentInformationModelFreightOptionsWeekendPickup() {
        return new FreightShipmentInformationModel.FreightOptions.WeekendPickup();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.FreightOptions.CustomsClearance }
     * 
     */
    public FreightShipmentInformationModel.FreightOptions.CustomsClearance createFreightShipmentInformationModelFreightOptionsCustomsClearance() {
        return new FreightShipmentInformationModel.FreightOptions.CustomsClearance();
    }

    /**
     * Create an instance of {@link PackageModel.PackageOptions.ProactiveResponse }
     * 
     */
    public PackageModel.PackageOptions.ProactiveResponse createPackageModelPackageOptionsProactiveResponse() {
        return new PackageModel.PackageOptions.ProactiveResponse();
    }

    /**
     * Create an instance of {@link InternationalDocumentationModel.Invoice }
     * 
     */
    public InternationalDocumentationModel.Invoice createInternationalDocumentationModelInvoice() {
        return new InternationalDocumentationModel.Invoice();
    }

    /**
     * Create an instance of {@link PackageModel.PackageOptions.DeclaredValue }
     * 
     */
    public PackageModel.PackageOptions.DeclaredValue createPackageModelPackageOptionsDeclaredValue() {
        return new PackageModel.PackageOptions.DeclaredValue();
    }

    /**
     * Create an instance of {@link ShipmentInformationModel.ShipmentOptions.ImportControl }
     * 
     */
    public ShipmentInformationModel.ShipmentOptions.ImportControl createShipmentInformationModelShipmentOptionsImportControl() {
        return new ShipmentInformationModel.ShipmentOptions.ImportControl();
    }

    /**
     * Create an instance of {@link FreightReferenceNumbersModel }
     * 
     */
    public FreightReferenceNumbersModel createFreightReferenceNumbersModel() {
        return new FreightReferenceNumbersModel();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.FreightOptions.ResidentialPickup }
     * 
     */
    public FreightShipmentInformationModel.FreightOptions.ResidentialPickup createFreightShipmentInformationModelFreightOptionsResidentialPickup() {
        return new FreightShipmentInformationModel.FreightOptions.ResidentialPickup();
    }

    /**
     * Create an instance of {@link ShipmentInformationModel.ShipmentOptions.QVN.Recipients }
     * 
     */
    public ShipmentInformationModel.ShipmentOptions.QVN.Recipients createShipmentInformationModelShipmentOptionsQVNRecipients() {
        return new ShipmentInformationModel.ShipmentOptions.QVN.Recipients();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.FreightOptions.DropOffAtUPSLocation }
     * 
     */
    public FreightShipmentInformationModel.FreightOptions.DropOffAtUPSLocation createFreightShipmentInformationModelFreightOptionsDropOffAtUPSLocation() {
        return new FreightShipmentInformationModel.FreightOptions.DropOffAtUPSLocation();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.FreightOptions.InsidePickup }
     * 
     */
    public FreightShipmentInformationModel.FreightOptions.InsidePickup createFreightShipmentInformationModelFreightOptionsInsidePickup() {
        return new FreightShipmentInformationModel.FreightOptions.InsidePickup();
    }

    /**
     * Create an instance of {@link ShipmentInformationModel.ShipmentOptions.SaturdayDelivery }
     * 
     */
    public ShipmentInformationModel.ShipmentOptions.SaturdayDelivery createShipmentInformationModelShipmentOptionsSaturdayDelivery() {
        return new ShipmentInformationModel.ShipmentOptions.SaturdayDelivery();
    }

    /**
     * Create an instance of {@link PackagesModel }
     * 
     */
    public PackagesModel createPackagesModel() {
        return new PackagesModel();
    }

    /**
     * Create an instance of {@link ShipmentInformationModel.ShipmentOptions.CommercialInvoiceRemoval }
     * 
     */
    public ShipmentInformationModel.ShipmentOptions.CommercialInvoiceRemoval createShipmentInformationModelShipmentOptionsCommercialInvoiceRemoval() {
        return new ShipmentInformationModel.ShipmentOptions.CommercialInvoiceRemoval();
    }

    /**
     * Create an instance of {@link ShipmentInformationModel.ShipmentOptions.ReturnService }
     * 
     */
    public ShipmentInformationModel.ShipmentOptions.ReturnService createShipmentInformationModelShipmentOptionsReturnService() {
        return new ShipmentInformationModel.ShipmentOptions.ReturnService();
    }

    /**
     * Create an instance of {@link GoodModel }
     * 
     */
    public GoodModel createGoodModel() {
        return new GoodModel();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.FreightOptions.HolidayPickup }
     * 
     */
    public FreightShipmentInformationModel.FreightOptions.HolidayPickup createFreightShipmentInformationModelFreightOptionsHolidayPickup() {
        return new FreightShipmentInformationModel.FreightOptions.HolidayPickup();
    }

    /**
     * Create an instance of {@link PackageModel.PackageOptions.ShipperRelease }
     * 
     */
    public PackageModel.PackageOptions.ShipperRelease createPackageModelPackageOptionsShipperRelease() {
        return new PackageModel.PackageOptions.ShipperRelease();
    }

    /**
     * Create an instance of {@link ShipmentModel }
     * 
     */
    public ShipmentModel createShipmentModel() {
        return new ShipmentModel();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.FreightOptions.AWBBOL.Emails }
     * 
     */
    public FreightShipmentInformationModel.FreightOptions.AWBBOL.Emails createFreightShipmentInformationModelFreightOptionsAWBBOLEmails() {
        return new FreightShipmentInformationModel.FreightOptions.AWBBOL.Emails();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.FreightOptions.LiftGateRequired }
     * 
     */
    public FreightShipmentInformationModel.FreightOptions.LiftGateRequired createFreightShipmentInformationModelFreightOptionsLiftGateRequired() {
        return new FreightShipmentInformationModel.FreightOptions.LiftGateRequired();
    }

    /**
     * Create an instance of {@link ShipmentInformationModel.GroundFreightPricing }
     * 
     */
    public ShipmentInformationModel.GroundFreightPricing createShipmentInformationModelGroundFreightPricing() {
        return new ShipmentInformationModel.GroundFreightPricing();
    }

    /**
     * Create an instance of {@link FreightEmailNotificationRecipientModel }
     * 
     */
    public FreightEmailNotificationRecipientModel createFreightEmailNotificationRecipientModel() {
        return new FreightEmailNotificationRecipientModel();
    }

    /**
     * Create an instance of {@link PackageModel.PackageOptions }
     * 
     */
    public PackageModel.PackageOptions createPackageModelPackageOptions() {
        return new PackageModel.PackageOptions();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.CountryOfOriginalManufacture }
     * 
     */
    public FreightShipmentInformationModel.CountryOfOriginalManufacture createFreightShipmentInformationModelCountryOfOriginalManufacture() {
        return new FreightShipmentInformationModel.CountryOfOriginalManufacture();
    }

    /**
     * Create an instance of {@link InternationalDocumentationModel.CO }
     * 
     */
    public InternationalDocumentationModel.CO createInternationalDocumentationModelCO() {
        return new InternationalDocumentationModel.CO();
    }

    /**
     * Create an instance of {@link HandlingUnitModel }
     * 
     */
    public HandlingUnitModel createHandlingUnitModel() {
        return new HandlingUnitModel();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.FreightOptions.LiftGateServiceForDelivery }
     * 
     */
    public FreightShipmentInformationModel.FreightOptions.LiftGateServiceForDelivery createFreightShipmentInformationModelFreightOptionsLiftGateServiceForDelivery() {
        return new FreightShipmentInformationModel.FreightOptions.LiftGateServiceForDelivery();
    }

    /**
     * Create an instance of {@link PackageModel.PackageOptions.USPSDeliveryConfirmation }
     * 
     */
    public PackageModel.PackageOptions.USPSDeliveryConfirmation createPackageModelPackageOptionsUSPSDeliveryConfirmation() {
        return new PackageModel.PackageOptions.USPSDeliveryConfirmation();
    }

    /**
     * Create an instance of {@link ShipmentInformationModel.ShipmentOptions }
     * 
     */
    public ShipmentInformationModel.ShipmentOptions createShipmentInformationModelShipmentOptions() {
        return new ShipmentInformationModel.ShipmentOptions();
    }

    /**
     * Create an instance of {@link InternationalDocumentationModel.Invoice.Charges }
     * 
     */
    public InternationalDocumentationModel.Invoice.Charges createInternationalDocumentationModelInvoiceCharges() {
        return new InternationalDocumentationModel.Invoice.Charges();
    }

    /**
     * Create an instance of {@link Shipments }
     * 
     */
    public Shipments createShipments() {
        return new Shipments();
    }

    /**
     * Create an instance of {@link PackageModel.ReferenceNumbers }
     * 
     */
    public PackageModel.ReferenceNumbers createPackageModelReferenceNumbers() {
        return new PackageModel.ReferenceNumbers();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.FreightOptions.LimitedAccessPickup }
     * 
     */
    public FreightShipmentInformationModel.FreightOptions.LimitedAccessPickup createFreightShipmentInformationModelFreightOptionsLimitedAccessPickup() {
        return new FreightShipmentInformationModel.FreightOptions.LimitedAccessPickup();
    }

    /**
     * Create an instance of {@link ShipmentInformationModel.ShipmentOptions.SaturdayPickup }
     * 
     */
    public ShipmentInformationModel.ShipmentOptions.SaturdayPickup createShipmentInformationModelShipmentOptionsSaturdayPickup() {
        return new ShipmentInformationModel.ShipmentOptions.SaturdayPickup();
    }

    /**
     * Create an instance of {@link PackageModel.PackageOptions.FlexibleParcelInsurance }
     * 
     */
    public PackageModel.PackageOptions.FlexibleParcelInsurance createPackageModelPackageOptionsFlexibleParcelInsurance() {
        return new PackageModel.PackageOptions.FlexibleParcelInsurance();
    }

    /**
     * Create an instance of {@link CODRemitInfoModel }
     * 
     */
    public CODRemitInfoModel createCODRemitInfoModel() {
        return new CODRemitInfoModel();
    }

    /**
     * Create an instance of {@link ShipmentInformationModel.ReferenceNumbers }
     * 
     */
    public ShipmentInformationModel.ReferenceNumbers createShipmentInformationModelReferenceNumbers() {
        return new ShipmentInformationModel.ReferenceNumbers();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.FreightOptions.ResidentialDelivery }
     * 
     */
    public FreightShipmentInformationModel.FreightOptions.ResidentialDelivery createFreightShipmentInformationModelFreightOptionsResidentialDelivery() {
        return new FreightShipmentInformationModel.FreightOptions.ResidentialDelivery();
    }

    /**
     * Create an instance of {@link PickupNotificationsforLTLRecipientModel }
     * 
     */
    public PickupNotificationsforLTLRecipientModel createPickupNotificationsforLTLRecipientModel() {
        return new PickupNotificationsforLTLRecipientModel();
    }

    /**
     * Create an instance of {@link HandlingUnitsModel }
     * 
     */
    public HandlingUnitsModel createHandlingUnitsModel() {
        return new HandlingUnitsModel();
    }

    /**
     * Create an instance of {@link ShipToModel }
     * 
     */
    public ShipToModel createShipToModel() {
        return new ShipToModel();
    }

    /**
     * Create an instance of {@link ShipmentInformationModel.ShipmentOptions.FoodItems }
     * 
     */
    public ShipmentInformationModel.ShipmentOptions.FoodItems createShipmentInformationModelShipmentOptionsFoodItems() {
        return new ShipmentInformationModel.ShipmentOptions.FoodItems();
    }

    /**
     * Create an instance of {@link PackageModel.Nonmachinable }
     * 
     */
    public PackageModel.Nonmachinable createPackageModelNonmachinable() {
        return new PackageModel.Nonmachinable();
    }

    /**
     * Create an instance of {@link InternationalDocumentationModel }
     * 
     */
    public InternationalDocumentationModel createInternationalDocumentationModel() {
        return new InternationalDocumentationModel();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.FreightOptions.SortingAndSegregating }
     * 
     */
    public FreightShipmentInformationModel.FreightOptions.SortingAndSegregating createFreightShipmentInformationModelFreightOptionsSortingAndSegregating() {
        return new FreightShipmentInformationModel.FreightOptions.SortingAndSegregating();
    }

    /**
     * Create an instance of {@link FreightReferenceNumberModel }
     * 
     */
    public FreightReferenceNumberModel createFreightReferenceNumberModel() {
        return new FreightReferenceNumberModel();
    }

    /**
     * Create an instance of {@link PackingListModel }
     * 
     */
    public PackingListModel createPackingListModel() {
        return new PackingListModel();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.FreightOptions.DangerousGoods }
     * 
     */
    public FreightShipmentInformationModel.FreightOptions.DangerousGoods createFreightShipmentInformationModelFreightOptionsDangerousGoods() {
        return new FreightShipmentInformationModel.FreightOptions.DangerousGoods();
    }

    /**
     * Create an instance of {@link ShipmentInformationModel.ShipmentOptions.COD }
     * 
     */
    public ShipmentInformationModel.ShipmentOptions.COD createShipmentInformationModelShipmentOptionsCOD() {
        return new ShipmentInformationModel.ShipmentOptions.COD();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.FreightOptions.DeliveryToDoor }
     * 
     */
    public FreightShipmentInformationModel.FreightOptions.DeliveryToDoor createFreightShipmentInformationModelFreightOptionsDeliveryToDoor() {
        return new FreightShipmentInformationModel.FreightOptions.DeliveryToDoor();
    }

    /**
     * Create an instance of {@link PackageModel.PackageOptions.COD }
     * 
     */
    public PackageModel.PackageOptions.COD createPackageModelPackageOptionsCOD() {
        return new PackageModel.PackageOptions.COD();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.FreightOptions.FreezableProtection }
     * 
     */
    public FreightShipmentInformationModel.FreightOptions.FreezableProtection createFreightShipmentInformationModelFreightOptionsFreezableProtection() {
        return new FreightShipmentInformationModel.FreightOptions.FreezableProtection();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.FreightOptions.COD }
     * 
     */
    public FreightShipmentInformationModel.FreightOptions.COD createFreightShipmentInformationModelFreightOptionsCOD() {
        return new FreightShipmentInformationModel.FreightOptions.COD();
    }

    /**
     * Create an instance of {@link ShipmentInformationModel.ShipmentOptions.ProactiveResponse }
     * 
     */
    public ShipmentInformationModel.ShipmentOptions.ProactiveResponse createShipmentInformationModelShipmentOptionsProactiveResponse() {
        return new ShipmentInformationModel.ShipmentOptions.ProactiveResponse();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.FreightOptions.AWBBOL }
     * 
     */
    public FreightShipmentInformationModel.FreightOptions.AWBBOL createFreightShipmentInformationModelFreightOptionsAWBBOL() {
        return new FreightShipmentInformationModel.FreightOptions.AWBBOL();
    }

    /**
     * Create an instance of {@link ShipmentInformationModel }
     * 
     */
    public ShipmentInformationModel createShipmentInformationModel() {
        return new ShipmentInformationModel();
    }

    /**
     * Create an instance of {@link ShipmentInformationModel.ShipmentOptions.NotifyBeforeDelivery }
     * 
     */
    public ShipmentInformationModel.ShipmentOptions.NotifyBeforeDelivery createShipmentInformationModelShipmentOptionsNotifyBeforeDelivery() {
        return new ShipmentInformationModel.ShipmentOptions.NotifyBeforeDelivery();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.FreightOptions.EmailNotification.Recipients }
     * 
     */
    public FreightShipmentInformationModel.FreightOptions.EmailNotification.Recipients createFreightShipmentInformationModelFreightOptionsEmailNotificationRecipients() {
        return new FreightShipmentInformationModel.FreightOptions.EmailNotification.Recipients();
    }

    /**
     * Create an instance of {@link PackageModel.PackageOptions.QVN }
     * 
     */
    public PackageModel.PackageOptions.QVN createPackageModelPackageOptionsQVN() {
        return new PackageModel.PackageOptions.QVN();
    }

    /**
     * Create an instance of {@link ShipmentInformationModel.ShipmentOptions.AdditionalHandling }
     * 
     */
    public ShipmentInformationModel.ShipmentOptions.AdditionalHandling createShipmentInformationModelShipmentOptionsAdditionalHandling() {
        return new ShipmentInformationModel.ShipmentOptions.AdditionalHandling();
    }

    /**
     * Create an instance of {@link ShipmentInformationModel.ShipmentOptions.HandlingCharge }
     * 
     */
    public ShipmentInformationModel.ShipmentOptions.HandlingCharge createShipmentInformationModelShipmentOptionsHandlingCharge() {
        return new ShipmentInformationModel.ShipmentOptions.HandlingCharge();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.FreightOptions.CallBeforeDelivery }
     * 
     */
    public FreightShipmentInformationModel.FreightOptions.CallBeforeDelivery createFreightShipmentInformationModelFreightOptionsCallBeforeDelivery() {
        return new FreightShipmentInformationModel.FreightOptions.CallBeforeDelivery();
    }

    /**
     * Create an instance of {@link ShipmentInformationModel.ShipmentOptions.UPSExchangeCollect }
     * 
     */
    public ShipmentInformationModel.ShipmentOptions.UPSExchangeCollect createShipmentInformationModelShipmentOptionsUPSExchangeCollect() {
        return new ShipmentInformationModel.ShipmentOptions.UPSExchangeCollect();
    }

    /**
     * Create an instance of {@link ShipmentInformationModel.ShipmentOptions.Refrigeration }
     * 
     */
    public ShipmentInformationModel.ShipmentOptions.Refrigeration createShipmentInformationModelShipmentOptionsRefrigeration() {
        return new ShipmentInformationModel.ShipmentOptions.Refrigeration();
    }

    /**
     * Create an instance of {@link PackageModel.PackageOptions.DeliveryConfirmation }
     * 
     */
    public PackageModel.PackageOptions.DeliveryConfirmation createPackageModelPackageOptionsDeliveryConfirmation() {
        return new PackageModel.PackageOptions.DeliveryConfirmation();
    }

    /**
     * Create an instance of {@link PackageModel.PackageOptions.Refrigeration }
     * 
     */
    public PackageModel.PackageOptions.Refrigeration createPackageModelPackageOptionsRefrigeration() {
        return new PackageModel.PackageOptions.Refrigeration();
    }

    /**
     * Create an instance of {@link PackageModel.GroundFreightPricing }
     * 
     */
    public PackageModel.GroundFreightPricing createPackageModelGroundFreightPricing() {
        return new PackageModel.GroundFreightPricing();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.FreightOptions.SaturdayDelivery }
     * 
     */
    public FreightShipmentInformationModel.FreightOptions.SaturdayDelivery createFreightShipmentInformationModelFreightOptionsSaturdayDelivery() {
        return new FreightShipmentInformationModel.FreightOptions.SaturdayDelivery();
    }

    /**
     * Create an instance of {@link ShipmentInformationModel.ShipmentOptions.PreAlertNotification.Telephone }
     * 
     */
    public ShipmentInformationModel.ShipmentOptions.PreAlertNotification.Telephone createShipmentInformationModelShipmentOptionsPreAlertNotificationTelephone() {
        return new ShipmentInformationModel.ShipmentOptions.PreAlertNotification.Telephone();
    }

    /**
     * Create an instance of {@link ShipmentInformationModel.WorldEaseShipment }
     * 
     */
    public ShipmentInformationModel.WorldEaseShipment createShipmentInformationModelWorldEaseShipment() {
        return new ShipmentInformationModel.WorldEaseShipment();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.FreightOptions }
     * 
     */
    public FreightShipmentInformationModel.FreightOptions createFreightShipmentInformationModelFreightOptions() {
        return new FreightShipmentInformationModel.FreightOptions();
    }

    /**
     * Create an instance of {@link ShipmentQVNRecipientAndNotificationModel }
     * 
     */
    public ShipmentQVNRecipientAndNotificationModel createShipmentQVNRecipientAndNotificationModel() {
        return new ShipmentQVNRecipientAndNotificationModel();
    }

    /**
     * Create an instance of {@link InternationalDocumentationModel.CN22 }
     * 
     */
    public InternationalDocumentationModel.CN22 createInternationalDocumentationModelCN22() {
        return new InternationalDocumentationModel.CN22();
    }

    /**
     * Create an instance of {@link PackageModel.PackageOptions.DangerousGoods }
     * 
     */
    public PackageModel.PackageOptions.DangerousGoods createPackageModelPackageOptionsDangerousGoods() {
        return new PackageModel.PackageOptions.DangerousGoods();
    }

    /**
     * Create an instance of {@link FreightCommodityModel }
     * 
     */
    public FreightCommodityModel createFreightCommodityModel() {
        return new FreightCommodityModel();
    }

    /**
     * Create an instance of {@link InternationalDocumentationModel.RequestDutiesAndTaxes }
     * 
     */
    public InternationalDocumentationModel.RequestDutiesAndTaxes createInternationalDocumentationModelRequestDutiesAndTaxes() {
        return new InternationalDocumentationModel.RequestDutiesAndTaxes();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.FreightOptions.ExtremeLength }
     * 
     */
    public FreightShipmentInformationModel.FreightOptions.ExtremeLength createFreightShipmentInformationModelFreightOptionsExtremeLength() {
        return new FreightShipmentInformationModel.FreightOptions.ExtremeLength();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.FreightOptions.DeclaredInsuredValue }
     * 
     */
    public FreightShipmentInformationModel.FreightOptions.DeclaredInsuredValue createFreightShipmentInformationModelFreightOptionsDeclaredInsuredValue() {
        return new FreightShipmentInformationModel.FreightOptions.DeclaredInsuredValue();
    }

    /**
     * Create an instance of {@link ShipmentInformationModel.ShipmentOptions.DeclaredValue }
     * 
     */
    public ShipmentInformationModel.ShipmentOptions.DeclaredValue createShipmentInformationModelShipmentOptionsDeclaredValue() {
        return new ShipmentInformationModel.ShipmentOptions.DeclaredValue();
    }

    /**
     * Create an instance of {@link ShipmentInformationModel.ShipmentOptions.PreAlertNotification.Email }
     * 
     */
    public ShipmentInformationModel.ShipmentOptions.PreAlertNotification.Email createShipmentInformationModelShipmentOptionsPreAlertNotificationEmail() {
        return new ShipmentInformationModel.ShipmentOptions.PreAlertNotification.Email();
    }

    /**
     * Create an instance of {@link UserFormItemModel }
     * 
     */
    public UserFormItemModel createUserFormItemModel() {
        return new UserFormItemModel();
    }

    /**
     * Create an instance of {@link PackingListItemModel }
     * 
     */
    public PackingListItemModel createPackingListItemModel() {
        return new PackingListItemModel();
    }

    /**
     * Create an instance of {@link PackageQVNRecipientAndNotificationModel }
     * 
     */
    public PackageQVNRecipientAndNotificationModel createPackageQVNRecipientAndNotificationModel() {
        return new PackageQVNRecipientAndNotificationModel();
    }

    /**
     * Create an instance of {@link ShipmentInformationModel.ShipmentOptions.UPSReturnsExchange }
     * 
     */
    public ShipmentInformationModel.ShipmentOptions.UPSReturnsExchange createShipmentInformationModelShipmentOptionsUPSReturnsExchange() {
        return new ShipmentInformationModel.ShipmentOptions.UPSReturnsExchange();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.FreightOptions.CustomsValue }
     * 
     */
    public FreightShipmentInformationModel.FreightOptions.CustomsValue createFreightShipmentInformationModelFreightOptionsCustomsValue() {
        return new FreightShipmentInformationModel.FreightOptions.CustomsValue();
    }

    /**
     * Create an instance of {@link FreightShipmentInformationModel.FreightOptions.WeekendDelivery }
     * 
     */
    public FreightShipmentInformationModel.FreightOptions.WeekendDelivery createFreightShipmentInformationModelFreightOptionsWeekendDelivery() {
        return new FreightShipmentInformationModel.FreightOptions.WeekendDelivery();
    }

}
