//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.31 at 09:45:21 AM CET 
//


package com.ups.xmlschema.ct.worldship.impexp.shipmentimport.v1_0_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PackageQVNRecipientAndNotificationModel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PackageQVNRecipientAndNotificationModel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="CompanyOrName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ContactName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Email" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InTransitNotification" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ShipOrReturnNotification" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ExceptionNotification" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DeliveryNotification" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PackageQVNRecipientAndNotificationModel", propOrder = {

})
public class PackageQVNRecipientAndNotificationModel {

    @XmlElement(name = "CompanyOrName")
    protected String companyOrName;
    @XmlElement(name = "ContactName")
    protected String contactName;
    @XmlElement(name = "Email")
    protected String email;
    @XmlElement(name = "InTransitNotification")
    protected String inTransitNotification;
    @XmlElement(name = "ShipOrReturnNotification")
    protected String shipOrReturnNotification;
    @XmlElement(name = "ExceptionNotification")
    protected String exceptionNotification;
    @XmlElement(name = "DeliveryNotification")
    protected String deliveryNotification;

    /**
     * Gets the value of the companyOrName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyOrName() {
        return companyOrName;
    }

    /**
     * Sets the value of the companyOrName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyOrName(String value) {
        this.companyOrName = value;
    }

    /**
     * Gets the value of the contactName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * Sets the value of the contactName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactName(String value) {
        this.contactName = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the inTransitNotification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInTransitNotification() {
        return inTransitNotification;
    }

    /**
     * Sets the value of the inTransitNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInTransitNotification(String value) {
        this.inTransitNotification = value;
    }

    /**
     * Gets the value of the shipOrReturnNotification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipOrReturnNotification() {
        return shipOrReturnNotification;
    }

    /**
     * Sets the value of the shipOrReturnNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipOrReturnNotification(String value) {
        this.shipOrReturnNotification = value;
    }

    /**
     * Gets the value of the exceptionNotification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExceptionNotification() {
        return exceptionNotification;
    }

    /**
     * Sets the value of the exceptionNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExceptionNotification(String value) {
        this.exceptionNotification = value;
    }

    /**
     * Gets the value of the deliveryNotification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeliveryNotification() {
        return deliveryNotification;
    }

    /**
     * Sets the value of the deliveryNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeliveryNotification(String value) {
        this.deliveryNotification = value;
    }

}
