//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.31 at 09:45:21 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ups.com/XMLSchema/CT/WorldShip/ImpExp/ShipmentImport/v1_0_0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ups.xmlschema.ct.worldship.impexp.shipmentimport.v1_0_0;
