//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.31 at 09:45:21 AM CET 
//


package com.ups.xmlschema.ct.worldship.impexp.shipmentimport.v1_0_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PickupNotificationsforLTLRecipientModel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PickupNotificationsforLTLRecipientModel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="EmailAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PickupScheduled" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Exception" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DriverEnRoute" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Pickedup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PickupNotificationsforLTLRecipientModel", propOrder = {

})
public class PickupNotificationsforLTLRecipientModel {

    @XmlElement(name = "EmailAddress")
    protected String emailAddress;
    @XmlElement(name = "PickupScheduled")
    protected String pickupScheduled;
    @XmlElement(name = "Exception")
    protected String exception;
    @XmlElement(name = "DriverEnRoute")
    protected String driverEnRoute;
    @XmlElement(name = "Pickedup")
    protected String pickedup;

    /**
     * Gets the value of the emailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * Sets the value of the emailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailAddress(String value) {
        this.emailAddress = value;
    }

    /**
     * Gets the value of the pickupScheduled property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPickupScheduled() {
        return pickupScheduled;
    }

    /**
     * Sets the value of the pickupScheduled property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPickupScheduled(String value) {
        this.pickupScheduled = value;
    }

    /**
     * Gets the value of the exception property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getException() {
        return exception;
    }

    /**
     * Sets the value of the exception property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setException(String value) {
        this.exception = value;
    }

    /**
     * Gets the value of the driverEnRoute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDriverEnRoute() {
        return driverEnRoute;
    }

    /**
     * Sets the value of the driverEnRoute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDriverEnRoute(String value) {
        this.driverEnRoute = value;
    }

    /**
     * Gets the value of the pickedup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPickedup() {
        return pickedup;
    }

    /**
     * Sets the value of the pickedup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPickedup(String value) {
        this.pickedup = value;
    }

}
