//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.31 at 09:45:21 AM CET 
//


package com.ups.xmlschema.ct.worldship.impexp.shipmentimport.v1_0_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ShipmentModel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ShipmentModel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="ShipmentKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ProfileName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PrinterID" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;all>
 *                   &lt;element name="LabelPrinterID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="InvoicePrinterID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="ReportPrinterID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="WorldEasePrinterID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="DangerousGoodsPrinterID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/all>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ShipTo" type="{http://www.ups.com/XMLSchema/CT/WorldShip/ImpExp/ShipmentImport/v1_0_0}ShipToModel" minOccurs="0"/>
 *         &lt;element name="ShipFrom" type="{http://www.ups.com/XMLSchema/CT/WorldShip/ImpExp/ShipmentImport/v1_0_0}ShipFromModel" minOccurs="0"/>
 *         &lt;element name="ThirdParty" type="{http://www.ups.com/XMLSchema/CT/WorldShip/ImpExp/ShipmentImport/v1_0_0}ThirdPartyModel" minOccurs="0"/>
 *         &lt;element name="ThirdPartyReceiver" type="{http://www.ups.com/XMLSchema/CT/WorldShip/ImpExp/ShipmentImport/v1_0_0}ThirdPartyReceiverModel" minOccurs="0"/>
 *         &lt;element name="Importer" type="{http://www.ups.com/XMLSchema/CT/WorldShip/ImpExp/ShipmentImport/v1_0_0}ImporterModel" minOccurs="0"/>
 *         &lt;element name="Producer" type="{http://www.ups.com/XMLSchema/CT/WorldShip/ImpExp/ShipmentImport/v1_0_0}ProducerModel" minOccurs="0"/>
 *         &lt;element name="IntermediateConsignee" type="{http://www.ups.com/XMLSchema/CT/WorldShip/ImpExp/ShipmentImport/v1_0_0}IntermediateConsigneeModel" minOccurs="0"/>
 *         &lt;element name="UltimateConsignee" type="{http://www.ups.com/XMLSchema/CT/WorldShip/ImpExp/ShipmentImport/v1_0_0}UltimateConsigneeModel" minOccurs="0"/>
 *         &lt;element name="CODRemitInfo" type="{http://www.ups.com/XMLSchema/CT/WorldShip/ImpExp/ShipmentImport/v1_0_0}CODRemitInfoModel" minOccurs="0"/>
 *         &lt;element name="ShipmentInformation" type="{http://www.ups.com/XMLSchema/CT/WorldShip/ImpExp/ShipmentImport/v1_0_0}ShipmentInformationModel" minOccurs="0"/>
 *         &lt;element name="Packages" type="{http://www.ups.com/XMLSchema/CT/WorldShip/ImpExp/ShipmentImport/v1_0_0}PackagesModel" minOccurs="0"/>
 *         &lt;element name="FreightShipmentInformation" type="{http://www.ups.com/XMLSchema/CT/WorldShip/ImpExp/ShipmentImport/v1_0_0}FreightShipmentInformationModel" minOccurs="0"/>
 *         &lt;element name="FreightCommodities" type="{http://www.ups.com/XMLSchema/CT/WorldShip/ImpExp/ShipmentImport/v1_0_0}FreightCommoditiesModel" minOccurs="0"/>
 *         &lt;element name="FreightReferenceNumbers" type="{http://www.ups.com/XMLSchema/CT/WorldShip/ImpExp/ShipmentImport/v1_0_0}FreightReferenceNumbersModel" minOccurs="0"/>
 *         &lt;element name="LTLTLLineItems" type="{http://www.ups.com/XMLSchema/CT/WorldShip/ImpExp/ShipmentImport/v1_0_0}LTLTLLineItemsModel" minOccurs="0"/>
 *         &lt;element name="InternationalDocumentation" type="{http://www.ups.com/XMLSchema/CT/WorldShip/ImpExp/ShipmentImport/v1_0_0}InternationalDocumentationModel" minOccurs="0"/>
 *         &lt;element name="Goods" type="{http://www.ups.com/XMLSchema/CT/WorldShip/ImpExp/ShipmentImport/v1_0_0}GoodsModel" minOccurs="0"/>
 *         &lt;element name="ShipperLetterOfInstruction" type="{http://www.ups.com/XMLSchema/CT/WorldShip/ImpExp/ShipmentImport/v1_0_0}ShipperLetterOfInstructionModel" minOccurs="0"/>
 *         &lt;element name="PackingList" type="{http://www.ups.com/XMLSchema/CT/WorldShip/ImpExp/ShipmentImport/v1_0_0}PackingListModel" minOccurs="0"/>
 *         &lt;element name="UserForms" type="{http://www.ups.com/XMLSchema/CT/WorldShip/ImpExp/ShipmentImport/v1_0_0}UserFormsModel" minOccurs="0"/>
 *         &lt;element name="HandlingUnits" type="{http://www.ups.com/XMLSchema/CT/WorldShip/ImpExp/ShipmentImport/v1_0_0}HandlingUnitsModel" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShipmentModel", propOrder = {

})
public class ShipmentModel {

    @XmlElement(name = "ShipmentKey")
    protected String shipmentKey;
    @XmlElement(name = "ProfileName")
    protected String profileName;
    @XmlElement(name = "PrinterID")
    protected ShipmentModel.PrinterID printerID;
    @XmlElement(name = "ShipTo")
    protected ShipToModel shipTo;
    @XmlElement(name = "ShipFrom")
    protected ShipFromModel shipFrom;
    @XmlElement(name = "ThirdParty")
    protected ThirdPartyModel thirdParty;
    @XmlElement(name = "ThirdPartyReceiver")
    protected ThirdPartyReceiverModel thirdPartyReceiver;
    @XmlElement(name = "Importer")
    protected ImporterModel importer;
    @XmlElement(name = "Producer")
    protected ProducerModel producer;
    @XmlElement(name = "IntermediateConsignee")
    protected IntermediateConsigneeModel intermediateConsignee;
    @XmlElement(name = "UltimateConsignee")
    protected UltimateConsigneeModel ultimateConsignee;
    @XmlElement(name = "CODRemitInfo")
    protected CODRemitInfoModel codRemitInfo;
    @XmlElement(name = "ShipmentInformation")
    protected ShipmentInformationModel shipmentInformation;
    @XmlElement(name = "Packages")
    protected PackagesModel packages;
    @XmlElement(name = "FreightShipmentInformation")
    protected FreightShipmentInformationModel freightShipmentInformation;
    @XmlElement(name = "FreightCommodities")
    protected FreightCommoditiesModel freightCommodities;
    @XmlElement(name = "FreightReferenceNumbers")
    protected FreightReferenceNumbersModel freightReferenceNumbers;
    @XmlElement(name = "LTLTLLineItems")
    protected LTLTLLineItemsModel ltltlLineItems;
    @XmlElement(name = "InternationalDocumentation")
    protected InternationalDocumentationModel internationalDocumentation;
    @XmlElement(name = "Goods")
    protected GoodsModel goods;
    @XmlElement(name = "ShipperLetterOfInstruction")
    protected ShipperLetterOfInstructionModel shipperLetterOfInstruction;
    @XmlElement(name = "PackingList")
    protected PackingListModel packingList;
    @XmlElement(name = "UserForms")
    protected UserFormsModel userForms;
    @XmlElement(name = "HandlingUnits")
    protected HandlingUnitsModel handlingUnits;

    /**
     * Gets the value of the shipmentKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShipmentKey() {
        return shipmentKey;
    }

    /**
     * Sets the value of the shipmentKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShipmentKey(String value) {
        this.shipmentKey = value;
    }

    /**
     * Gets the value of the profileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProfileName() {
        return profileName;
    }

    /**
     * Sets the value of the profileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProfileName(String value) {
        this.profileName = value;
    }

    /**
     * Gets the value of the printerID property.
     * 
     * @return
     *     possible object is
     *     {@link ShipmentModel.PrinterID }
     *     
     */
    public ShipmentModel.PrinterID getPrinterID() {
        return printerID;
    }

    /**
     * Sets the value of the printerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipmentModel.PrinterID }
     *     
     */
    public void setPrinterID(ShipmentModel.PrinterID value) {
        this.printerID = value;
    }

    /**
     * Gets the value of the shipTo property.
     * 
     * @return
     *     possible object is
     *     {@link ShipToModel }
     *     
     */
    public ShipToModel getShipTo() {
        return shipTo;
    }

    /**
     * Sets the value of the shipTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipToModel }
     *     
     */
    public void setShipTo(ShipToModel value) {
        this.shipTo = value;
    }

    /**
     * Gets the value of the shipFrom property.
     * 
     * @return
     *     possible object is
     *     {@link ShipFromModel }
     *     
     */
    public ShipFromModel getShipFrom() {
        return shipFrom;
    }

    /**
     * Sets the value of the shipFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipFromModel }
     *     
     */
    public void setShipFrom(ShipFromModel value) {
        this.shipFrom = value;
    }

    /**
     * Gets the value of the thirdParty property.
     * 
     * @return
     *     possible object is
     *     {@link ThirdPartyModel }
     *     
     */
    public ThirdPartyModel getThirdParty() {
        return thirdParty;
    }

    /**
     * Sets the value of the thirdParty property.
     * 
     * @param value
     *     allowed object is
     *     {@link ThirdPartyModel }
     *     
     */
    public void setThirdParty(ThirdPartyModel value) {
        this.thirdParty = value;
    }

    /**
     * Gets the value of the thirdPartyReceiver property.
     * 
     * @return
     *     possible object is
     *     {@link ThirdPartyReceiverModel }
     *     
     */
    public ThirdPartyReceiverModel getThirdPartyReceiver() {
        return thirdPartyReceiver;
    }

    /**
     * Sets the value of the thirdPartyReceiver property.
     * 
     * @param value
     *     allowed object is
     *     {@link ThirdPartyReceiverModel }
     *     
     */
    public void setThirdPartyReceiver(ThirdPartyReceiverModel value) {
        this.thirdPartyReceiver = value;
    }

    /**
     * Gets the value of the importer property.
     * 
     * @return
     *     possible object is
     *     {@link ImporterModel }
     *     
     */
    public ImporterModel getImporter() {
        return importer;
    }

    /**
     * Sets the value of the importer property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImporterModel }
     *     
     */
    public void setImporter(ImporterModel value) {
        this.importer = value;
    }

    /**
     * Gets the value of the producer property.
     * 
     * @return
     *     possible object is
     *     {@link ProducerModel }
     *     
     */
    public ProducerModel getProducer() {
        return producer;
    }

    /**
     * Sets the value of the producer property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProducerModel }
     *     
     */
    public void setProducer(ProducerModel value) {
        this.producer = value;
    }

    /**
     * Gets the value of the intermediateConsignee property.
     * 
     * @return
     *     possible object is
     *     {@link IntermediateConsigneeModel }
     *     
     */
    public IntermediateConsigneeModel getIntermediateConsignee() {
        return intermediateConsignee;
    }

    /**
     * Sets the value of the intermediateConsignee property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntermediateConsigneeModel }
     *     
     */
    public void setIntermediateConsignee(IntermediateConsigneeModel value) {
        this.intermediateConsignee = value;
    }

    /**
     * Gets the value of the ultimateConsignee property.
     * 
     * @return
     *     possible object is
     *     {@link UltimateConsigneeModel }
     *     
     */
    public UltimateConsigneeModel getUltimateConsignee() {
        return ultimateConsignee;
    }

    /**
     * Sets the value of the ultimateConsignee property.
     * 
     * @param value
     *     allowed object is
     *     {@link UltimateConsigneeModel }
     *     
     */
    public void setUltimateConsignee(UltimateConsigneeModel value) {
        this.ultimateConsignee = value;
    }

    /**
     * Gets the value of the codRemitInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CODRemitInfoModel }
     *     
     */
    public CODRemitInfoModel getCODRemitInfo() {
        return codRemitInfo;
    }

    /**
     * Sets the value of the codRemitInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CODRemitInfoModel }
     *     
     */
    public void setCODRemitInfo(CODRemitInfoModel value) {
        this.codRemitInfo = value;
    }

    /**
     * Gets the value of the shipmentInformation property.
     * 
     * @return
     *     possible object is
     *     {@link ShipmentInformationModel }
     *     
     */
    public ShipmentInformationModel getShipmentInformation() {
        return shipmentInformation;
    }

    /**
     * Sets the value of the shipmentInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipmentInformationModel }
     *     
     */
    public void setShipmentInformation(ShipmentInformationModel value) {
        this.shipmentInformation = value;
    }

    /**
     * Gets the value of the packages property.
     * 
     * @return
     *     possible object is
     *     {@link PackagesModel }
     *     
     */
    public PackagesModel getPackages() {
        return packages;
    }

    /**
     * Sets the value of the packages property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackagesModel }
     *     
     */
    public void setPackages(PackagesModel value) {
        this.packages = value;
    }

    /**
     * Gets the value of the freightShipmentInformation property.
     * 
     * @return
     *     possible object is
     *     {@link FreightShipmentInformationModel }
     *     
     */
    public FreightShipmentInformationModel getFreightShipmentInformation() {
        return freightShipmentInformation;
    }

    /**
     * Sets the value of the freightShipmentInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreightShipmentInformationModel }
     *     
     */
    public void setFreightShipmentInformation(FreightShipmentInformationModel value) {
        this.freightShipmentInformation = value;
    }

    /**
     * Gets the value of the freightCommodities property.
     * 
     * @return
     *     possible object is
     *     {@link FreightCommoditiesModel }
     *     
     */
    public FreightCommoditiesModel getFreightCommodities() {
        return freightCommodities;
    }

    /**
     * Sets the value of the freightCommodities property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreightCommoditiesModel }
     *     
     */
    public void setFreightCommodities(FreightCommoditiesModel value) {
        this.freightCommodities = value;
    }

    /**
     * Gets the value of the freightReferenceNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link FreightReferenceNumbersModel }
     *     
     */
    public FreightReferenceNumbersModel getFreightReferenceNumbers() {
        return freightReferenceNumbers;
    }

    /**
     * Sets the value of the freightReferenceNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link FreightReferenceNumbersModel }
     *     
     */
    public void setFreightReferenceNumbers(FreightReferenceNumbersModel value) {
        this.freightReferenceNumbers = value;
    }

    /**
     * Gets the value of the ltltlLineItems property.
     * 
     * @return
     *     possible object is
     *     {@link LTLTLLineItemsModel }
     *     
     */
    public LTLTLLineItemsModel getLTLTLLineItems() {
        return ltltlLineItems;
    }

    /**
     * Sets the value of the ltltlLineItems property.
     * 
     * @param value
     *     allowed object is
     *     {@link LTLTLLineItemsModel }
     *     
     */
    public void setLTLTLLineItems(LTLTLLineItemsModel value) {
        this.ltltlLineItems = value;
    }

    /**
     * Gets the value of the internationalDocumentation property.
     * 
     * @return
     *     possible object is
     *     {@link InternationalDocumentationModel }
     *     
     */
    public InternationalDocumentationModel getInternationalDocumentation() {
        return internationalDocumentation;
    }

    /**
     * Sets the value of the internationalDocumentation property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternationalDocumentationModel }
     *     
     */
    public void setInternationalDocumentation(InternationalDocumentationModel value) {
        this.internationalDocumentation = value;
    }

    /**
     * Gets the value of the goods property.
     * 
     * @return
     *     possible object is
     *     {@link GoodsModel }
     *     
     */
    public GoodsModel getGoods() {
        return goods;
    }

    /**
     * Sets the value of the goods property.
     * 
     * @param value
     *     allowed object is
     *     {@link GoodsModel }
     *     
     */
    public void setGoods(GoodsModel value) {
        this.goods = value;
    }

    /**
     * Gets the value of the shipperLetterOfInstruction property.
     * 
     * @return
     *     possible object is
     *     {@link ShipperLetterOfInstructionModel }
     *     
     */
    public ShipperLetterOfInstructionModel getShipperLetterOfInstruction() {
        return shipperLetterOfInstruction;
    }

    /**
     * Sets the value of the shipperLetterOfInstruction property.
     * 
     * @param value
     *     allowed object is
     *     {@link ShipperLetterOfInstructionModel }
     *     
     */
    public void setShipperLetterOfInstruction(ShipperLetterOfInstructionModel value) {
        this.shipperLetterOfInstruction = value;
    }

    /**
     * Gets the value of the packingList property.
     * 
     * @return
     *     possible object is
     *     {@link PackingListModel }
     *     
     */
    public PackingListModel getPackingList() {
        return packingList;
    }

    /**
     * Sets the value of the packingList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PackingListModel }
     *     
     */
    public void setPackingList(PackingListModel value) {
        this.packingList = value;
    }

    /**
     * Gets the value of the userForms property.
     * 
     * @return
     *     possible object is
     *     {@link UserFormsModel }
     *     
     */
    public UserFormsModel getUserForms() {
        return userForms;
    }

    /**
     * Sets the value of the userForms property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserFormsModel }
     *     
     */
    public void setUserForms(UserFormsModel value) {
        this.userForms = value;
    }

    /**
     * Gets the value of the handlingUnits property.
     * 
     * @return
     *     possible object is
     *     {@link HandlingUnitsModel }
     *     
     */
    public HandlingUnitsModel getHandlingUnits() {
        return handlingUnits;
    }

    /**
     * Sets the value of the handlingUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link HandlingUnitsModel }
     *     
     */
    public void setHandlingUnits(HandlingUnitsModel value) {
        this.handlingUnits = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;all>
     *         &lt;element name="LabelPrinterID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="InvoicePrinterID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="ReportPrinterID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="WorldEasePrinterID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="DangerousGoodsPrinterID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/all>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {

    })
    public static class PrinterID {

        @XmlElement(name = "LabelPrinterID")
        protected String labelPrinterID;
        @XmlElement(name = "InvoicePrinterID")
        protected String invoicePrinterID;
        @XmlElement(name = "ReportPrinterID")
        protected String reportPrinterID;
        @XmlElement(name = "WorldEasePrinterID")
        protected String worldEasePrinterID;
        @XmlElement(name = "DangerousGoodsPrinterID")
        protected String dangerousGoodsPrinterID;

        /**
         * Gets the value of the labelPrinterID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLabelPrinterID() {
            return labelPrinterID;
        }

        /**
         * Sets the value of the labelPrinterID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLabelPrinterID(String value) {
            this.labelPrinterID = value;
        }

        /**
         * Gets the value of the invoicePrinterID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInvoicePrinterID() {
            return invoicePrinterID;
        }

        /**
         * Sets the value of the invoicePrinterID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInvoicePrinterID(String value) {
            this.invoicePrinterID = value;
        }

        /**
         * Gets the value of the reportPrinterID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getReportPrinterID() {
            return reportPrinterID;
        }

        /**
         * Sets the value of the reportPrinterID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setReportPrinterID(String value) {
            this.reportPrinterID = value;
        }

        /**
         * Gets the value of the worldEasePrinterID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWorldEasePrinterID() {
            return worldEasePrinterID;
        }

        /**
         * Sets the value of the worldEasePrinterID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWorldEasePrinterID(String value) {
            this.worldEasePrinterID = value;
        }

        /**
         * Gets the value of the dangerousGoodsPrinterID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDangerousGoodsPrinterID() {
            return dangerousGoodsPrinterID;
        }

        /**
         * Sets the value of the dangerousGoodsPrinterID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDangerousGoodsPrinterID(String value) {
            this.dangerousGoodsPrinterID = value;
        }

    }

}
