//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.31 at 09:45:21 AM CET 
//


package com.ups.xmlschema.ct.worldship.impexp.shipmentimport.v1_0_0;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ShipperLetterOfInstructionModel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ShipperLetterOfInstructionModel">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="PrintSLI" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RoutedExportTransaction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UltimateConsigneeSameAsShipTo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IntermediateConsignee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IsPartiesToTransactionRelated" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DDTCRegistrationNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SME" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EligiblePartyCertificateNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="USMLCategoryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DDTCQuantity" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="UnitOfMeasure" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DDTCLicenseLineNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TelephoneNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="EmailAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AttachedCommercialInvoice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AttachedCertificateOfOrigin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AttachedPackingList" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AttachedLetterOfCredit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AttachedBankingSightDraft" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AttachedImportLicense" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AttachedExportLicense" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AttachedDangerousGoodsDeclaration" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AttachedGBLOption" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AttachedGBLValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ProFormaInvoice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CertificateOfOrigin" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ConsularInvoice" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="BankingSightDraft" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="InsuranceCertificate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ExportLicense" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SpecialInstructionsForShipment" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ExtraDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CertificateOfOriginNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="DulyAuthorizedOfficerEmployee" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ShipperLetterOfInstructionModel", propOrder = {

})
public class ShipperLetterOfInstructionModel {

    @XmlElement(name = "PrintSLI")
    protected String printSLI;
    @XmlElement(name = "RoutedExportTransaction")
    protected String routedExportTransaction;
    @XmlElement(name = "UltimateConsigneeSameAsShipTo")
    protected String ultimateConsigneeSameAsShipTo;
    @XmlElement(name = "IntermediateConsignee")
    protected String intermediateConsignee;
    @XmlElement(name = "IsPartiesToTransactionRelated")
    protected String isPartiesToTransactionRelated;
    @XmlElement(name = "DDTCRegistrationNumber")
    protected String ddtcRegistrationNumber;
    @XmlElement(name = "SME")
    protected String sme;
    @XmlElement(name = "EligiblePartyCertificateNumber")
    protected String eligiblePartyCertificateNumber;
    @XmlElement(name = "USMLCategoryCode")
    protected String usmlCategoryCode;
    @XmlElement(name = "DDTCQuantity")
    protected String ddtcQuantity;
    @XmlElement(name = "UnitOfMeasure")
    protected String unitOfMeasure;
    @XmlElement(name = "DDTCLicenseLineNumber")
    protected String ddtcLicenseLineNumber;
    @XmlElement(name = "Title")
    protected String title;
    @XmlElement(name = "TelephoneNumber")
    protected String telephoneNumber;
    @XmlElement(name = "EmailAddress")
    protected String emailAddress;
    @XmlElement(name = "AttachedCommercialInvoice")
    protected String attachedCommercialInvoice;
    @XmlElement(name = "AttachedCertificateOfOrigin")
    protected String attachedCertificateOfOrigin;
    @XmlElement(name = "AttachedPackingList")
    protected String attachedPackingList;
    @XmlElement(name = "AttachedLetterOfCredit")
    protected String attachedLetterOfCredit;
    @XmlElement(name = "AttachedBankingSightDraft")
    protected String attachedBankingSightDraft;
    @XmlElement(name = "AttachedImportLicense")
    protected String attachedImportLicense;
    @XmlElement(name = "AttachedExportLicense")
    protected String attachedExportLicense;
    @XmlElement(name = "AttachedDangerousGoodsDeclaration")
    protected String attachedDangerousGoodsDeclaration;
    @XmlElement(name = "AttachedGBLOption")
    protected String attachedGBLOption;
    @XmlElement(name = "AttachedGBLValue")
    protected String attachedGBLValue;
    @XmlElement(name = "ProFormaInvoice")
    protected String proFormaInvoice;
    @XmlElement(name = "CertificateOfOrigin")
    protected String certificateOfOrigin;
    @XmlElement(name = "ConsularInvoice")
    protected String consularInvoice;
    @XmlElement(name = "BankingSightDraft")
    protected String bankingSightDraft;
    @XmlElement(name = "InsuranceCertificate")
    protected String insuranceCertificate;
    @XmlElement(name = "ExportLicense")
    protected String exportLicense;
    @XmlElement(name = "SpecialInstructionsForShipment")
    protected String specialInstructionsForShipment;
    @XmlElement(name = "ExtraDescription")
    protected String extraDescription;
    @XmlElement(name = "CertificateOfOriginNumber")
    protected String certificateOfOriginNumber;
    @XmlElement(name = "DulyAuthorizedOfficerEmployee")
    protected String dulyAuthorizedOfficerEmployee;

    /**
     * Gets the value of the printSLI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrintSLI() {
        return printSLI;
    }

    /**
     * Sets the value of the printSLI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrintSLI(String value) {
        this.printSLI = value;
    }

    /**
     * Gets the value of the routedExportTransaction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoutedExportTransaction() {
        return routedExportTransaction;
    }

    /**
     * Sets the value of the routedExportTransaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoutedExportTransaction(String value) {
        this.routedExportTransaction = value;
    }

    /**
     * Gets the value of the ultimateConsigneeSameAsShipTo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUltimateConsigneeSameAsShipTo() {
        return ultimateConsigneeSameAsShipTo;
    }

    /**
     * Sets the value of the ultimateConsigneeSameAsShipTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUltimateConsigneeSameAsShipTo(String value) {
        this.ultimateConsigneeSameAsShipTo = value;
    }

    /**
     * Gets the value of the intermediateConsignee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntermediateConsignee() {
        return intermediateConsignee;
    }

    /**
     * Sets the value of the intermediateConsignee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntermediateConsignee(String value) {
        this.intermediateConsignee = value;
    }

    /**
     * Gets the value of the isPartiesToTransactionRelated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsPartiesToTransactionRelated() {
        return isPartiesToTransactionRelated;
    }

    /**
     * Sets the value of the isPartiesToTransactionRelated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsPartiesToTransactionRelated(String value) {
        this.isPartiesToTransactionRelated = value;
    }

    /**
     * Gets the value of the ddtcRegistrationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDDTCRegistrationNumber() {
        return ddtcRegistrationNumber;
    }

    /**
     * Sets the value of the ddtcRegistrationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDDTCRegistrationNumber(String value) {
        this.ddtcRegistrationNumber = value;
    }

    /**
     * Gets the value of the sme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSME() {
        return sme;
    }

    /**
     * Sets the value of the sme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSME(String value) {
        this.sme = value;
    }

    /**
     * Gets the value of the eligiblePartyCertificateNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEligiblePartyCertificateNumber() {
        return eligiblePartyCertificateNumber;
    }

    /**
     * Sets the value of the eligiblePartyCertificateNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEligiblePartyCertificateNumber(String value) {
        this.eligiblePartyCertificateNumber = value;
    }

    /**
     * Gets the value of the usmlCategoryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUSMLCategoryCode() {
        return usmlCategoryCode;
    }

    /**
     * Sets the value of the usmlCategoryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUSMLCategoryCode(String value) {
        this.usmlCategoryCode = value;
    }

    /**
     * Gets the value of the ddtcQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDDTCQuantity() {
        return ddtcQuantity;
    }

    /**
     * Sets the value of the ddtcQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDDTCQuantity(String value) {
        this.ddtcQuantity = value;
    }

    /**
     * Gets the value of the unitOfMeasure property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUnitOfMeasure() {
        return unitOfMeasure;
    }

    /**
     * Sets the value of the unitOfMeasure property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUnitOfMeasure(String value) {
        this.unitOfMeasure = value;
    }

    /**
     * Gets the value of the ddtcLicenseLineNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDDTCLicenseLineNumber() {
        return ddtcLicenseLineNumber;
    }

    /**
     * Sets the value of the ddtcLicenseLineNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDDTCLicenseLineNumber(String value) {
        this.ddtcLicenseLineNumber = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the telephoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTelephoneNumber() {
        return telephoneNumber;
    }

    /**
     * Sets the value of the telephoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTelephoneNumber(String value) {
        this.telephoneNumber = value;
    }

    /**
     * Gets the value of the emailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * Sets the value of the emailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailAddress(String value) {
        this.emailAddress = value;
    }

    /**
     * Gets the value of the attachedCommercialInvoice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttachedCommercialInvoice() {
        return attachedCommercialInvoice;
    }

    /**
     * Sets the value of the attachedCommercialInvoice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttachedCommercialInvoice(String value) {
        this.attachedCommercialInvoice = value;
    }

    /**
     * Gets the value of the attachedCertificateOfOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttachedCertificateOfOrigin() {
        return attachedCertificateOfOrigin;
    }

    /**
     * Sets the value of the attachedCertificateOfOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttachedCertificateOfOrigin(String value) {
        this.attachedCertificateOfOrigin = value;
    }

    /**
     * Gets the value of the attachedPackingList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttachedPackingList() {
        return attachedPackingList;
    }

    /**
     * Sets the value of the attachedPackingList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttachedPackingList(String value) {
        this.attachedPackingList = value;
    }

    /**
     * Gets the value of the attachedLetterOfCredit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttachedLetterOfCredit() {
        return attachedLetterOfCredit;
    }

    /**
     * Sets the value of the attachedLetterOfCredit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttachedLetterOfCredit(String value) {
        this.attachedLetterOfCredit = value;
    }

    /**
     * Gets the value of the attachedBankingSightDraft property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttachedBankingSightDraft() {
        return attachedBankingSightDraft;
    }

    /**
     * Sets the value of the attachedBankingSightDraft property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttachedBankingSightDraft(String value) {
        this.attachedBankingSightDraft = value;
    }

    /**
     * Gets the value of the attachedImportLicense property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttachedImportLicense() {
        return attachedImportLicense;
    }

    /**
     * Sets the value of the attachedImportLicense property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttachedImportLicense(String value) {
        this.attachedImportLicense = value;
    }

    /**
     * Gets the value of the attachedExportLicense property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttachedExportLicense() {
        return attachedExportLicense;
    }

    /**
     * Sets the value of the attachedExportLicense property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttachedExportLicense(String value) {
        this.attachedExportLicense = value;
    }

    /**
     * Gets the value of the attachedDangerousGoodsDeclaration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttachedDangerousGoodsDeclaration() {
        return attachedDangerousGoodsDeclaration;
    }

    /**
     * Sets the value of the attachedDangerousGoodsDeclaration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttachedDangerousGoodsDeclaration(String value) {
        this.attachedDangerousGoodsDeclaration = value;
    }

    /**
     * Gets the value of the attachedGBLOption property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttachedGBLOption() {
        return attachedGBLOption;
    }

    /**
     * Sets the value of the attachedGBLOption property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttachedGBLOption(String value) {
        this.attachedGBLOption = value;
    }

    /**
     * Gets the value of the attachedGBLValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttachedGBLValue() {
        return attachedGBLValue;
    }

    /**
     * Sets the value of the attachedGBLValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttachedGBLValue(String value) {
        this.attachedGBLValue = value;
    }

    /**
     * Gets the value of the proFormaInvoice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProFormaInvoice() {
        return proFormaInvoice;
    }

    /**
     * Sets the value of the proFormaInvoice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProFormaInvoice(String value) {
        this.proFormaInvoice = value;
    }

    /**
     * Gets the value of the certificateOfOrigin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificateOfOrigin() {
        return certificateOfOrigin;
    }

    /**
     * Sets the value of the certificateOfOrigin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificateOfOrigin(String value) {
        this.certificateOfOrigin = value;
    }

    /**
     * Gets the value of the consularInvoice property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsularInvoice() {
        return consularInvoice;
    }

    /**
     * Sets the value of the consularInvoice property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsularInvoice(String value) {
        this.consularInvoice = value;
    }

    /**
     * Gets the value of the bankingSightDraft property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBankingSightDraft() {
        return bankingSightDraft;
    }

    /**
     * Sets the value of the bankingSightDraft property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBankingSightDraft(String value) {
        this.bankingSightDraft = value;
    }

    /**
     * Gets the value of the insuranceCertificate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInsuranceCertificate() {
        return insuranceCertificate;
    }

    /**
     * Sets the value of the insuranceCertificate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInsuranceCertificate(String value) {
        this.insuranceCertificate = value;
    }

    /**
     * Gets the value of the exportLicense property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExportLicense() {
        return exportLicense;
    }

    /**
     * Sets the value of the exportLicense property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExportLicense(String value) {
        this.exportLicense = value;
    }

    /**
     * Gets the value of the specialInstructionsForShipment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialInstructionsForShipment() {
        return specialInstructionsForShipment;
    }

    /**
     * Sets the value of the specialInstructionsForShipment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialInstructionsForShipment(String value) {
        this.specialInstructionsForShipment = value;
    }

    /**
     * Gets the value of the extraDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtraDescription() {
        return extraDescription;
    }

    /**
     * Sets the value of the extraDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtraDescription(String value) {
        this.extraDescription = value;
    }

    /**
     * Gets the value of the certificateOfOriginNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificateOfOriginNumber() {
        return certificateOfOriginNumber;
    }

    /**
     * Sets the value of the certificateOfOriginNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificateOfOriginNumber(String value) {
        this.certificateOfOriginNumber = value;
    }

    /**
     * Gets the value of the dulyAuthorizedOfficerEmployee property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDulyAuthorizedOfficerEmployee() {
        return dulyAuthorizedOfficerEmployee;
    }

    /**
     * Sets the value of the dulyAuthorizedOfficerEmployee property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDulyAuthorizedOfficerEmployee(String value) {
        this.dulyAuthorizedOfficerEmployee = value;
    }

}
